import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import { LuDot } from 'react-icons/lu'

function Aboutus() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LoaderUniversal>
                    <LanguageHeader />
                    <div className='col-md-12 background_color_universal'>
                        <div className='col-md-12 background_headerpp universal_padding'>
                            <div className='row pt-4'>
                                <div className='col-md-2 col-5'>
                                    <Link href="/" className='link_style'>
                                        <img className='img-fluid width_gp_l' src='/imagess/logo.png' />
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2'>
                                    <Link href="/" className='link_style'>
                                          <p className='m-0 p-0 font_header2'>Home</p>
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2' >
                                      <Link href="/Blogs" className='link_style'>
 <p className='m-0 p-0 font_header2'>Blog</p>
</Link>
                                </div>
                                <div className='col-md-1 pt-2 col-3'>
                                    <p className='m-0 p-0 font_header2'>Help Center</p>
                                </div>

                            </div>
                            <div className='col-md-12 mt-5 pb-5'>
                                <div className='row'>
                                    <div className='col-md-6 m-auto '>
                                        <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                            About Us
                                        </p>
                                        <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                            <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> About Us</span>
                                        </p>
                                    </div>
                                    <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                        <img className='img-fluid' data-aos="zoom-in" src='/imagess/money.png' />
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div className='col-md-12  background_header2  mt-5 '>

                            <div className='col-md-12 universal_padding pb-5'>
                                <div className='row mt-5   pb-5' >
                                    <div className='col-md-6'>
                                        <div className='col-md-12'>
                                            <img className='img-fluid' src='/imagess/banner-m2.png' />
                                        </div>
                                    </div>
                                    <div className='col-md-6 m-auto '>
                                        <div className='col-md-12 text-start mt-md-0 mt-5'>
                                            <p className='font_GBP' data-aos="zoom-in-up" data-aos-duration="4000">Transfer & Deposite Money Anytime,<br />
                                                Anywhere In The World.</p>
                                        </div>
                                        <div className='col-md-12 text-start'>
                                            <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                Welcome to YafPay, where financial convenience knows no bounds. With our innovative banking app, YafPay, you can seamlessly transfer and deposit money anytime, anywhere in the world, putting the power of global transactions in the palm of your hand. We offer the following services:

                                            </p>
                                            <div className='row'>
                                                <div className='col-md-6'>
                                                    <div className='row mt-3'>
                                                        <div className='col-md-2 col-1 '>
                                                            <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                        </div>
                                                        <div className='col-md-10 ps-0 col-11 pt-1'>
                                                            <p className='m-0 p-0 subb_head ' data-aos="fade-right" data-aos-duration="3000">
                                                                Powerful Mobile & Online App
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div className='row mt-3'>
                                                        <div className='col-md-2 col-1 '>
                                                            <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                        </div>
                                                        <div className='col-md-10 ps-0 col-11 pt-1'>
                                                            <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000">
                                                                Commitment Free
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div className='row mt-3'>
                                                        <div className='col-md-2 col-1 '>
                                                            <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                        </div>
                                                        <div className='col-md-10 ps-0 col-11 pt-1'>
                                                            <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000" >
                                                                Full Data Privacy Compliance.
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-6'>
                                                    <div className='row mt-3'>
                                                        <div className='col-md-2 col-1 '>
                                                            <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                        </div>
                                                        <div className='col-md-10 ps-0 col-11 pt-1'>
                                                            <p className='m-0 p-0 subb_head ' data-aos="fade-right" data-aos-duration="3000">
                                                                Powerful Mobile & Online App
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div className='row mt-3'>
                                                        <div className='col-md-2 col-1 '>
                                                            <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                        </div>
                                                        <div className='col-md-10 ps-0 col-11 pt-1'>
                                                            <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000">
                                                                Commitment Free
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div className='row mt-3'>
                                                        <div className='col-md-2 col-1 '>
                                                            <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                        </div>
                                                        <div className='col-md-10 ps-0 col-11 pt-1'>
                                                            <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000" >
                                                                Full Data Privacy Compliance.
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div className='col-md-12 background_blue py-5  universal_padding' >
                            <p className='m-0 p-0 text_banner41'>Your Benefits</p>
                            <p className='m-0 p-0 text_banner4' data-aos="zoom-in-up" data-aos-duration="4000">Take The Stress Out Of Managing<br /> Property And Money</p>
                            <div className='row mt-5 px-3 px-md-0'>
                                <div className='col-md-6  '>
                                    <div className='col-md-12 py-4 px-4 bg-white rounded'>
                                        <div className='row'>
                                            <div className='col-md-2 col-2'>
                                                <img className='img-fluid' src='/imagess/air.png' />
                                            </div>
                                            <div className='col-md-10 col-10 ps-0 carddd'>
                                                <p className='m-0 p-0'>Global Coverage</p>
                                                <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                    Experience limitless financial possibilities with YafPay's global coverage, ensuring you can manage your money seamlessly across borders, without constraints or limitations.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-6 mt-4 mt-md-0 '>
                                    <div className='col-md-12 py-4 px-4 bg-white rounded'>
                                        <div className='row'>
                                            <div className='col-md-2 col-2'>
                                                <img className='img-fluid' src='/imagess/casj.png' />
                                            </div>
                                            <div className='col-md-10 col-10 ps-0 carddd'>
                                                <p className='m-0 p-0'>Lowest Fee</p>
                                                <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                    Unlock the advantage of the lowest fees in the industry with YafPay, ensuring you get the most from your money while enjoying a cost-effective and efficient banking experience.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-6  mt-4  '>
                                    <div className='col-md-12 py-4 px-4 bg-white rounded'>
                                        <div className='row'>
                                            <div className='col-md-2 col-2'>
                                                <img className='img-fluid' src='/imagess/cash.png' />
                                            </div>
                                            <div className='col-md-10 col-10 ps-0 carddd'>
                                                <p className='m-0 p-0'>Simple Transfer Methods</p>
                                                <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                    Easily send money anywhere with YafPay. Our system is straightforward and easy to use, ensuring your transactions are simple and hassle-free.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-6  mt-4  '>
                                    <div className='col-md-12 py-4 px-4 bg-white rounded'>
                                        <div className='row'>
                                            <div className='col-md-2 col-2'>
                                                <img className='img-fluid' src='/imagess/sack.png' />
                                            </div>
                                            <div className='col-md-10 col-10 ps-0 carddd'>
                                                <p className='m-0 p-0'>Instant Processing</p>
                                                <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                    Experience swift results with YafPay, where your transactions are processed instantly, giving you the speed and efficiency you need for seamless banking.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-6  mt-4 mb-md-5 '>
                                    <div className='col-md-12 py-4 px-4 bg-white rounded'>
                                        <div className='row'>
                                            <div className='col-md-2 col-2'>
                                                <img className='img-fluid' src='/imagess/cc.png' />
                                            </div>
                                            <div className='col-md-10 col-10 ps-0 carddd'>
                                                <p className='m-0 p-0'>Bank-level Security</p>
                                                <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                    Trust YafPay to prioritize your security. We implement bank-level measures to ensure your financial information is protected and your transactions remain confidential.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-6  mt-4 mb-md-5 '>
                                    <div className='col-md-12 py-4 px-4 bg-white rounded'>
                                        <div className='row'>
                                            <div className='col-md-2 col-2'>
                                                <img className='img-fluid' src='/imagess/cs.png' />
                                            </div>
                                            <div className='col-md-10 col-10 ps-0 carddd'>
                                                <p className='m-0 p-0'>Global 24/7 Support</p>
                                                <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">
                                                    Count on YafPay for round-the-clock support, ensuring assistance is always at your fingertips whenever you need it. Our commitment to your satisfaction knows no time constraints.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col-md-12  background_header3 pt-5  '>
                            <div className='row universal_padding'>
                                <div className='col-md-6'>
                                    <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/girls.png' />
                                </div>
                                <div className='col-md-6 m-md-auto mt-5 ps-4 px-md-0'>
                                    <div className='col-md-12  text-start'>
                                        <p className='font_GBP mb-0' data-aos="zoom-in-up" data-aos-duration="4000">A Fully Integrated Suite Of Every Product Payments</p>
                                        <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                                            Discover the power of YafPay as a unified platform, seamlessly integrating a comprehensive suite of payment products. From transfers to deposits, YafPay is your all-in-one solution, simplifying your financial experience with a fully integrated suite of products.
                                        </p>
                                    </div>
                                    <div className='row mt-4'>
                                        <div className='col-md-6'>
                                            <div className='col-md-12'>
                                                <img className='img-fluid' src='/imagess/kl.png' />
                                                <p className='m-0 p-0 split'>Split The Necessities</p>
                                                <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                                                    There are many variations of passages of Lorem Ipsum amet avoilble but majority
                                                    have suffered alteration in some form.
                                                </p>
                                            </div>
                                        </div>
                                        <div className='col-md-6'>
                                            <div className='col-md-12'>
                                                <img className='img-fluid' src='/imagess/ip.png' />
                                                <p className='m-0 p-0 split'>Pay For Business</p>
                                                <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                                                    There are many variations of passages of Lorem Ipsum amet avoilble but majority
                                                    have suffered alteration in some form.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-12 position_new pe-0'>
                                    <img className='img-fluid wisth_circle' src='/imagess/side.png' />
                                </div>
                            </div>


                        </div>
                        <div className='col-md-12 mt-5 pt-5 mb-5 pb-5'>
                            <div className='row universal_padding'>
                                <div className='col-md-6 m-auto'>
                                    <div className='col-md-12  text-start'>
                                        <p className='font_GBP mb-0' data-aos="zoom-in-up" data-aos-duration="4000">Why people choose us</p>
                                        <p className='font_GBP3 mb-2' data-aos="zoom-in-up" data-aos-duration="4000">Banking Payments</p>
                                        <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                                            There are many variations of passages of Lorem Ipsum amet avoilble but majority
                                            have suffered alteration in some form, by injected humur or randomise words which
                                            don't sure amet sit dolor quras alto lorem.
                                        </p>
                                        <p className=' mb-1 points_currency' data-aos="zoom-in-left" data-aos-duration="6000">
                                            Cards that work all across the world.
                                        </p>
                                        <p className=' mb-1 points_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                                            Highest Returns on your investments.
                                        </p>
                                        <p className=' mb-1 points_currency ' data-aos="zoom-in-left" data-aos-duration="2000">
                                            No ATM fees. No minimum balance. No overdrafts.
                                        </p>
                                    </div>
                                    <div className='col-md-12 mt-4' data-aos="zoom-in-left" data-aos-duration="4000">
                                        <img className='img-fluid' src='/imagess/signup.png' />
                                    </div>
                                </div>
                                <div className='col-md-6 text-center mt-5 mt-0'>
                                    <img className='img-fluid' src='/imagess/banner-v2.png' />
                                </div>
                            </div>
                        </div>
                        <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                            <div className='row universal_padding'>
                                <div className='col-md-6 px-md-4'>
                                    <img className='img-fluid' src='/imagess/b4.png' data-aos="fade-right" data-aos-duration="6000" />
                                </div>
                                <div className='col-md-6 m-auto'>
                                    <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                        Download our App to get all kinds of
                                        banking benefits from anywhere
                                    </p>
                                    <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                        <img className='img-fluid width_gp' src='/imagess/googleplay.png' />
                                        <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.png' />
                                    </div>
                                </div>

                            </div>


                        </div>
                        <Footer />
                    </div>
                </LoaderUniversal>
            </main>
        </>
    )
}

export default Aboutus