import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import { LuDot } from "react-icons/lu";
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import MobileHeader from '@/Components/MobileHeader/MobileHeader'

function Acceptablepolicy() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <LoaderUniversal>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LanguageHeader />
                <div className='col-md-12 background_color_universal'>
                    <div className='col-md-12 background_headerpp universal_padding'>
                        <div className='row display_pc pt-4'>
                            <div className='col-md-2 col-5'>
                                <Link href="/" className='link_style'>
                                    <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                                </Link>
                            </div>
                            <div className='col-md-1 pt-2 col-2'>
                                <Link href="/" className='link_style'>
                                    <p className='m-0 p-0 font_header2'>Home</p>
                                </Link>
                            </div>
                            <div className='col-md-1 pt-2 col-2' >
                                <Link href="/Blogs" className='link_style'>
                                    <p className='m-0 p-0 font_header2'>Blog</p>
                                </Link>
                            </div>
                            <div className='col-md-1 pt-2 col-3'>
                                <p className='m-0 p-0 font_header2'>Help Center</p>
                            </div>

                        </div>
                        <div className='display_mob'>
                            <MobileHeader />
                        </div>
                        <div className='col-md-12 mt-5 pb-5'>
                            <div className='row'>
                                <div className='col-md-6 m-auto '>
                                    <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                        Acceptable Use Policy
                                    </p>
                                    <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                        <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> Acceptable Use Policy</span>
                                    </p>
                                </div>
                                <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                    <img className='img-fluid' data-aos="zoom-in" src='/imagess/acc.webp' />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className='col-md-12 universal_padding'>
                        <p className='m-0 p-0 yapay_head'>Acceptable Use Policy</p>
                        <p className='m-0 p-0 yapay_head1'>
                            Yafpay provides foreign virtual accounts to customers thus enables customers to receive and make
                            payments subject to certain eligibility requirements which may depend on your occupation, country of
                            residency or incorporation, applicable anti-money laundering regulations, Yafpay risk management
                            policies or procedures and other factors used by us to determine such eligibility from time to time at our
                            sole discretion.
                            To avoid fraud and money laundering activities we do not accept users with unknown sources of income
                            or ambiguous lines of businesses/ occupations. Our users are encouraged to show reasons why they need
                            a foreign virtual account. Yafpay reserves the right to refuse your virtual account application and Yafpay
                            will only verify your application if on viewing your submitted documents and details we are satisfied that
                            the nature of business being carried out by a user is such that he/she will be using a foreign virtual
                            account for transactions.
                            Our platform is to be used in:
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>receiving your salary or wages;</li>
                                <li>receiving payouts from e-commerce and freelancer platforms;</li>
                                <li>receiving payments from family, friends or other people you know for personal purposes;</li>
                                <li>receiving payments from your clients and other third parties for the purpose of business payments</li>
                            </ul>
                        </p>
                    </div>

                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>RESTRICTIONS ON USING OUR PLATFORM</p>
                        <p className='m-0 p-0 yapay_head2'>Transacting on your own account</p>
                        <p className='m-0 p-0 yapay_head1'>
                            All activities under a Yafpay account shall be deemed as activities carried out by the registered user. You
                            shall only use the services to transact on your own account and not on behalf of any other person or
                            entity. You agree not to authorize any other person or entity to use your user name and password or
                            mobile device to access the Services. You are solely responsible for the maintenance, confidentiality, and
                            security of your username, password, and other User Information.
                            Yafpay would not be responsible for any losses arising out of the loss or theft of your User Information or
                            your mobile device or from unauthorized or fraudulent transactions associated with your Yafpay Virtual
                            Account. If you suspect or become aware of any unauthorized activity or access to your username,
                            password, or mobile device, you must contact us immediately to restrict or block your account.

                        </p>

                        <p className='m-0 p-0 yapay_head2 mt-4'>One account per person or entity</p>
                        <p className='m-0 p-0 yapay_head1'>
                            You may only open one Yafpay account unless we have agreed in writing, the opening of additional
                            accounts. Yafpay may refuse the creation of duplicate accounts for the same user. Where duplicate
                            accounts are detected, Yafpay may close or merge these duplicate accounts at its sole discretion.
                        </p>
                        <p className='m-0 p-0 yapay_head5 mt-4'>1. Restricted activities</p>
                        <p className='m-0 p-0 yapay_head1'>
                            You may use our platform only for lawful purposes. You may not use our platform:
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>in any way that breaches any applicable local, national, or international law or regulation, or
                                    causes Yafpay to breach any applicable law or regulation</li>
                                <li> in any way that is unlawful or fraudulent, or has any unlawful or fraudulent purpose or effect;</li>
                                <li> for the purpose of harming or attempting to harm minors in any way;</li>
                                <li> for anything that is abusive, harmful, or does not comply with our content standards;
                                </li>
                                <li> for any unsolicited or unauthorised advertising, promotional material, or any other form of spam;
                                </li>
                                <li> to deal in harmful programs such as viruses, spyware, or similar computer code designed to adversely affect the operation of any computer software or hardware;
                                </li>
                                <li> Not to use your Yafpay virtual account in a manner that is likely to result in complaints, disputes,
                                    reversals, chargebacks, or other liabilities to Yafpay, other Customers, third parties, or you.</li>
                            </ul>
                        </p>

                        <p className='m-0 p-0 yapay_head5 mt-4'>2. Restricted line of businesses</p>
                        <p className='m-0 p-0 yapay_head1'>
                            Grey does not service transactions relating to the following Restricted Lines of Business including but not limited to:                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>Illegal Activities- Any criminal or illegal act that breaches any applicable local, national, or international law or regulation. – e.g. Illegal narcotics, child pornography, human </li>
                                <li>trafficking, terrorist financing, stolen goods, illegal wildlife trade</li>
                                <li>Gambling</li>
                                <li>Currency exchange, including crypto-currencies and FX</li>
                                <li>Investment or “get rich quick” merchants, businesses or programs.</li>
                                <li>Crowdfunding</li>
                                <li>Counterfeiting and Copyright infringement</li>
                                <li>Reselling event tickets</li>
                                <li>sale and purchase of firearms, firearm parts or accessories, ammunition, weapons or knives</li>
                                <li>Adult entertainment and/or adult content websites</li>
                                <li>All Drugs and Pharma</li>
                                <li>unlicensed financial services, stocks or other securities;</li>
                                <li>Items or services that promote hate, violence, racial intolerance</li>
                                <li>any product or service that is illegal or marketed or sold in such a way as to create liability to Yafpay.</li>
                            </ul>
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            Yafpay may pre-approve the use of its Services in connection with some of the above, following review
                            and examination of circumstances thereof, and subject to its sole discretion. Acts, products or services
                            which constitute a breach of applicable laws or regulations will not be supported under any
                            circumstances
                        </p>
                    </div>

                    <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                        <div className='row universal_padding'>
                            <div className='col-md-6 px-md-4'>
                                <img className='img-fluid' src='/imagess/b4.webp' data-aos="fade-right" data-aos-duration="6000" />
                            </div>
                            <div className='col-md-6 m-auto'>
                                <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                    Download our App to get all kinds of
                                    banking benefits from anywhere
                                </p>
                                <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                    <img className='img-fluid width_gp' src='/imagess/googleplay.webp' />
                                    <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.webp' />
                                </div>
                            </div>

                        </div>


                    </div>

                    <Footer />
                </div>
            </main>
        </LoaderUniversal>
    )
}

export default Acceptablepolicy