import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect, useState } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import Button from 'react-bootstrap/Button';
import Collapse from 'react-bootstrap/Collapse';

function AllServices() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);

    const [open1, setOpen1] = useState(false);
    const [open2, setOpen2] = useState(false);
    const [open3, setOpen3] = useState(false);
    const [open4, setOpen4] = useState(false);
    const [open5, setOpen5] = useState(false);
    const [open6, setOpen6] = useState(false);

    return (
        <>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LoaderUniversal>
                    <LanguageHeader />
                    <div className='col-md-12 background_color_universal'>
                        <div className='col-md-12 background_header1 universal_padding'>
                            <div className='row pt-4'>
                                <div className='col-md-2 col-5'>
                                    <Link href="/" className='link_style'>
                                        <img className='img-fluid width_gp_l' src='/imagess/logo.png' />
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2'>
                                    <Link href="/" className='link_style'>
                                          <p className='m-0 p-0 font_header2'>Home</p>
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2' >
                                      <Link href="/Blogs" className='link_style'>
 <p className='m-0 p-0 font_header2'>Blog</p>
</Link>
                                </div>
                                <div className='col-md-1 pt-2 col-3'>
                                    <p className='m-0 p-0 font_header2'>Help Center</p>
                                </div>

                            </div>
                            <div className='col-md-12 mt-5 pb-5'>
                                <div className='row'>
                                    <div className='col-md-6 m-auto '>
                                        <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                            Get paid like A<br />
                                            local
                                        </p>
                                        <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                            Open a global bank account for free to receive and make<br />
                                            foreign payments or convert currencies, all in one place
                                        </p>
                                        <div className='col-md-12 mt-md-1 pt-4'>
                                            <img className='img-fluid width_gp' src='/imagess/googleplay.png' data-aos="fade-right" data-aos-duration="4000" />
                                            <img className='img-fluid ps-md-4 ps-2 width_gp' src='/imagess/apple.png' data-aos="fade-right" data-aos-duration="3000" />
                                        </div>
                                        <div className='col-md-12 mt-md-3 mt-4'>
                                            <div className='row'>
                                                <div className='col-md-3 col-4 '>
                                                    <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/people.png' />
                                                </div>
                                                <div className='col-md-9 col-8 m-auto'>
                                                    <p className='m-0 p-0' data-aos="fade-left" data-aos-duration="3000"><span className='fivek'>500K+</span><span className='people ps-2'>People already trusted us.</span></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                        <img className='img-fluid' data-aos="zoom-in" src='/imagess/banner-s1.png' />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className='col-md-12  background_header2 pt-5 mt-5  pb-5 '>
                            <div className='row universal_padding pb-5'>
                                <div className='col-md-6 m-auto'>
                                    <p className='mb-2 text_section6' data-aos="fade-right" data-aos-duration="4000">
                                        We operate our banking services in<br /> many countries around the world
                                    </p>
                                    <div className='col-md-12 '>
                                        <p className='m-0 p-0 subb_head ' data-aos="fade-right" data-aos-duration="3000">
                                            Lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat nisl bibendum vitae<br />
                                            consequat. Nisl ut sed accumsan congue tempus fringilla diam arcu. Venenatis nulla
                                        </p>
                                        <div className='row'>
                                            <div className='col-md-6'>
                                                <div className='row mt-3'>
                                                    <div className='col-md-2 col-1 '>
                                                        <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                    </div>
                                                    <div className='col-md-10 ps-0 col-11 pt-1'>
                                                        <p className='m-0 p-0 subb_head ' data-aos="fade-right" data-aos-duration="3000">
                                                            Powerful Mobile & Online App
                                                        </p>
                                                    </div>
                                                </div>
                                                <div className='row mt-3'>
                                                    <div className='col-md-2 col-1 '>
                                                        <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                    </div>
                                                    <div className='col-md-10 ps-0 col-11 pt-1'>
                                                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000">
                                                            Commitment Free
                                                        </p>
                                                    </div>
                                                </div>
                                                <div className='row mt-3'>
                                                    <div className='col-md-2 col-1 '>
                                                        <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                    </div>
                                                    <div className='col-md-10 ps-0 col-11 pt-1'>
                                                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000" >
                                                            Full Data Privacy Compliance.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className='col-md-6'>
                                                <div className='row mt-3'>
                                                    <div className='col-md-2 col-1 '>
                                                        <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                    </div>
                                                    <div className='col-md-10 ps-0 col-11 pt-1'>
                                                        <p className='m-0 p-0 subb_head ' data-aos="fade-right" data-aos-duration="3000">
                                                            Powerful Mobile & Online App
                                                        </p>
                                                    </div>
                                                </div>
                                                <div className='row mt-3'>
                                                    <div className='col-md-2 col-1 '>
                                                        <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                    </div>
                                                    <div className='col-md-10 ps-0 col-11 pt-1'>
                                                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000">
                                                            Commitment Free
                                                        </p>
                                                    </div>
                                                </div>
                                                <div className='row mt-3'>
                                                    <div className='col-md-2 col-1 '>
                                                        <img className='img-fluid' src='/imagess/check.png' data-aos="fade-right" data-aos-duration="4000" />
                                                    </div>
                                                    <div className='col-md-10 ps-0 col-11 pt-1'>
                                                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000" >
                                                            Full Data Privacy Compliance.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div className='col-md-6 text-end mt-5 mt-md-0'>
                                    <img className='img-fluid' src='/imagess/banner-s2.png' data-aos="fade-left" data-aos-duration="6000" />
                                </div>

                            </div>
                        </div>
                        <div className='col-md-12 background_blue py-5  universal_padding' >
                            <p className='m-0 p-0 text_banner4' data-aos="zoom-in-up" data-aos-duration="4000">How to open a free foreign bank account</p>
                            <div className='row mt-5 px-3 px-md-0'>
                                <div className='col-md-4 mt-md-0 mt-3'>
                                    <div className='row'>
                                        <div className='col-md-1 col-1 px-0'>
                                            <img className='img-fluid'
                                                data-aos="fade-right" data-aos-duration="4000"
                                                src='/imagess/one.png' />
                                        </div>
                                        <div className='col-md-11 col-11'>
                                            <p className='m-0 p-0 register_text' data-aos="fade-right" data-aos-duration="4000" >Register in minutes</p>
                                            <p className='m-0 p-0 reg_text_1' data-aos="fade-right" data-aos-duration="3000" >
                                                Sign up online, or in our app with your<br />
                                                email address
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-4 mt-md-0 mt-3'>
                                    <div className='row'>
                                        <div className='col-md-1 col-1 px-0'>
                                            <img className='img-fluid'
                                                data-aos="fade-right" data-aos-duration="4000"
                                                src='/imagess/one.png' />
                                        </div>
                                        <div className='col-md-11 col-11'>
                                            <p className='m-0 p-0 register_text' data-aos="fade-right" data-aos-duration="4000" >Complete KYC verifications</p>
                                            <p className='m-0 p-0 reg_text_1' data-aos="fade-right" data-aos-duration="3000" >
                                                Verify your identity using your government-<br />
                                                issued ID
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-4 mt-md-0 mt-3'>
                                    <div className='row'>
                                        <div className='col-md-1 col-1 px-0'>
                                            <img className='img-fluid'
                                                data-aos="fade-right" data-aos-duration="4000"
                                                src='/imagess/one.png' />
                                        </div>
                                        <div className='col-md-11 col-11'>
                                            <p className='m-0 p-0 register_text' data-aos="fade-right" data-aos-duration="4000" >Get your virtual account</p>
                                            <p className='m-0 p-0 reg_text_1' data-aos="fade-right" data-aos-duration="3000" >
                                                Share your account details to get paid, or spend<br />
                                                around the world with your debit card.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className='col-md-12 mt-5 px-2 px-md-0'>
                                <img className='img-fluid' data-aos="fade-right" data-aos-duration="3000" src='/imagess/register.png' />
                            </div>
                        </div>
                        <div className='col-md-12  background_header3 pt-5  '>
                            <div className='row universal_padding'>
                                <div className='col-md-12  text-center'>
                                    <p className='font_GBP mb-0' data-aos="zoom-in-up" data-aos-duration="4000">Frequently ask question</p>
                                    <p className='font_GBP1' data-aos="zoom-in-up" data-aos-duration="4000">Just find your answers below</p>
                                </div>
                                <div className='col-md-4'>
                                    <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/banner-s3.png' />
                                </div>
                                <div className='col-md-8 px-md-5 mt-5 m-md-auto'>
                                    <div className='col-md-12 background_card_new11   bg-white'
                                        onClick={() => setOpen1(!open1)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open1}
                                    >
                                        <div className={`col-md-12 ${open1 ? "background_active_drop" : ""} py-2 px-3`}>
                                        <div className='row'>
                                            <div className='col-md-8 col-10 m-auto'>
                                                <p className='m-0 p-0 new_c_text'>1. What kind of financial consultancy you need?</p>
                                            </div>
                                            <div className='col-md-4 col-2 text-end'>
                                                <img className='img-fluid'  src={`/imagess/${open1 ? "minus" : "pluss"}.png`} />
                                            </div>
                                        </div>
                                        </div>
                                        <Collapse in={open1} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen2(!open2)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open2}
                                    >
                                        <div className={`col-md-12 ${open2 ? "background_active_drop" : ""} py-2 px-3`}>
                                        <div className='row'>
                                            <div className='col-md-8 col-10 m-auto'>
                                                <p className='m-0 p-0 new_c_text'>2. What Is The Best Features And Services We Deliver?</p>
                                            </div>
                                            <div className='col-md-4 col-2 text-end'>
                                                <img className='img-fluid'  src={`/imagess/${open2 ? "minus" : "pluss"}.png`} />
                                            </div>
                                        </div>
                                        </div>
                                        <Collapse in={open2} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen3(!open3)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open3}
                                    >
                                        <div className={`col-md-12 ${open3 ? "background_active_drop" : ""} py-2 px-3`}>
                                        <div className='row'>
                                            <div className='col-md-8 col-10 m-auto'>
                                                <p className='m-0 p-0 new_c_text'>3. What Are The Objectives Of This Service?</p>
                                            </div>
                                            <div className='col-md-4 col-2 text-end'>
                                                <img className='img-fluid'  src={`/imagess/${open3 ? "minus" : "pluss"}.png`} />
                                            </div>
                                        </div>
                                        </div>
                                        <Collapse in={open3} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen4(!open4)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open4}
                                    >
                                        <div className={`col-md-12 ${open4 ? "background_active_drop" : ""} py-2 px-3`}>
                                        <div className='row'>
                                            <div className='col-md-8 col-10 m-auto'>
                                                <p className='m-0 p-0 new_c_text'>4. What Is A Multi-currency Card?</p>
                                            </div>
                                            <div className='col-md-4 col-2 text-end'>
                                                <img className='img-fluid'  src={`/imagess/${open4 ? "minus" : "pluss"}.png`} />
                                            </div>
                                        </div>
                                        </div>
                                        <Collapse in={open4} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen5(!open5)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open5}
                                    >
                                        <div className={`col-md-12 ${open5 ? "background_active_drop" : ""} py-2 px-3`}>
                                        <div className='row'>
                                            <div className='col-md-8 col-10 m-auto'>
                                                <p className='m-0 p-0 new_c_text'>5. What Is The Best Features And Services We Deliver?</p>
                                            </div>
                                            <div className='col-md-4 col-2 text-end'>
                                                <img className='img-fluid'  src={`/imagess/${open5 ? "minus" : "pluss"}.png`} />
                                            </div>
                                        </div>
                                        </div>
                                        <Collapse in={open5} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen6(!open6)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open6}
                                    >
                                        <div className={`col-md-12 ${open6 ? "background_active_drop" : ""} py-2 px-3`}>
                                        <div className='row'>
                                            <div className='col-md-8 col-10 m-auto'>
                                                <p className='m-0 p-0 new_c_text'>6. What Happened To The Borderless Account?</p>
                                            </div>
                                            <div className='col-md-4 col-2 text-end'>
                                                <img className='img-fluid'  src={`/imagess/${open6 ? "minus" : "pluss"}.png`} />
                                            </div>
                                        </div>
                                        </div>
                                        <Collapse in={open6} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                   
                                </div>
                                <div className='col-md-12 position_new pe-0'>
                                    <img className='img-fluid wisth_circle' src='/imagess/side.png' />
                                </div>
                            </div>


                        </div>

                        <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                            <div className='row universal_padding'>
                                <div className='col-md-6 px-md-4'>
                                    <img className='img-fluid' src='/imagess/b4.png' data-aos="fade-right" data-aos-duration="6000" />
                                </div>
                                <div className='col-md-6 m-auto'>
                                    <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                        Download our App to get all kinds of
                                        banking benefits from anywhere
                                    </p>
                                    <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                        <img className='img-fluid width_gp' src='/imagess/googleplay.png' />
                                        <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.png' />
                                    </div>
                                </div>

                            </div>


                        </div>
                        <Footer />
                    </div>
                </LoaderUniversal>
            </main>
        </>
    )
}

export default AllServices