import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import { LuDot } from 'react-icons/lu'
import MobileHeader from '@/Components/MobileHeader/MobileHeader'

function Blogs() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LoaderUniversal>
                    <LanguageHeader />
                    <div className='col-md-12 background_color_universal'>
                        <div className='col-md-12 background_headerpp universal_padding'>
                            <div className='row display_pc pt-4'>
                                <div className='col-md-2 col-5'>
                                    <Link href="/" className='link_style'>
                                        <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2'>
                                    <Link href="/" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Home</p>
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2' >
                                    <Link href="/Blogs" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Blog</p>
                                    </Link>
                                </div>
                               <div className='col-md-1 pt-2 col-3'>
                                    <Link href="/helpcenter" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Help Center</p>
                                    </Link>
                                </div>

                            </div>
                            <div className='display_mob'>
                                <MobileHeader />
                            </div>
                            <div className='col-md-12 mt-5 pb-5'>
                                <div className='row'>
                                    <div className='col-md-6 m-auto '>
                                        <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                            YAFPAY Blogs
                                        </p>
                                        <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                            <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> YAFPAY Blogs</span>
                                        </p>
                                        <div className='col-md-7 mt-5'>
                                            <input className='form-control form-control-lg  search_article' type='text' placeholder='Search an article' />
                                        </div>
                                    </div>

                                    <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                        <img className='img-fluid' data-aos="zoom-in" src='/imagess/contact.webp' />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col-md-12 universal_padding'>
                            <div className='row'>
                                <div className='col-md-8'>
                                    <div className='col-md-12'>
                                        <div className='row'>
                                            <div className='col-md-6 mt-4 '>
                                                <Link href="/Blogsdetail" className='link_style'>
                                                    <div className='col-md-12 px-md-3'>
                                                        <div className='col-md-12 '>
                                                            <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                                            <div className='row px-4 neg_mar_top'>
                                                                <div className='col-md-6 col-6'>
                                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                                </div>
                                                                <div className='col-md-4 col-4 text-end'>
                                                                    <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                                </div>
                                                                <div className='col-md-2 col-2 text-end'>
                                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div className='col-md-12 mt-2 pe-md-5'>
                                                            <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                                Culture: A Foundation for Success</p>
                                                            <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                                about working at your company is? Depending on
                                                                where you work, there are a few possible reasons.</p>
                                                        </div>
                                                        <div className='col-md-12'>
                                                            <img className='img-fluid' src='/imagess/readmore.webp' />
                                                        </div>
                                                    </div>
                                                </Link>
                                            </div>
                                            <div className='col-md-6 mt-4 '>
                                                <div className='col-md-12 px-md-3'>
                                                    <div className='col-md-12 '>
                                                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                                        <div className='row px-4 neg_mar_top'>
                                                            <div className='col-md-6 col-6'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                            </div>
                                                            <div className='col-md-4 col-4 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                            </div>
                                                            <div className='col-md-2 col-2 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className='col-md-12 mt-2 pe-md-5'>
                                                        <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                            Culture: A Foundation for Success</p>
                                                        <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                            about working at your company is? Depending on
                                                            where you work, there are a few possible reasons.</p>
                                                    </div>
                                                    <div className='col-md-12'>
                                                        <img className='img-fluid' src='/imagess/readmore.webp' />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className='col-md-6 mt-4 '>
                                                <div className='col-md-12 px-md-3'>
                                                    <div className='col-md-12 '>
                                                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                                        <div className='row px-4 neg_mar_top'>
                                                            <div className='col-md-6 col-6'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                            </div>
                                                            <div className='col-md-4 col-4 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                            </div>
                                                            <div className='col-md-2 col-2 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className='col-md-12 mt-2 pe-md-5'>
                                                        <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                            Culture: A Foundation for Success</p>
                                                        <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                            about working at your company is? Depending on
                                                            where you work, there are a few possible reasons.</p>
                                                    </div>
                                                    <div className='col-md-12'>
                                                        <img className='img-fluid' src='/imagess/readmore.webp' />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className='col-md-6 mt-4 '>
                                                <div className='col-md-12 px-md-3'>
                                                    <div className='col-md-12 '>
                                                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                                        <div className='row px-4 neg_mar_top'>
                                                            <div className='col-md-6 col-6'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                            </div>
                                                            <div className='col-md-4 col-4 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                            </div>
                                                            <div className='col-md-2 col-2 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className='col-md-12 mt-2 pe-md-5'>
                                                        <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                            Culture: A Foundation for Success</p>
                                                        <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                            about working at your company is? Depending on
                                                            where you work, there are a few possible reasons.</p>
                                                    </div>
                                                    <div className='col-md-12'>
                                                        <img className='img-fluid' src='/imagess/readmore.webp' />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className='col-md-6 mt-4 '>
                                                <div className='col-md-12 px-md-3'>
                                                    <div className='col-md-12 '>
                                                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                                        <div className='row px-4 neg_mar_top'>
                                                            <div className='col-md-6 col-6'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                            </div>
                                                            <div className='col-md-4 col-4 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                            </div>
                                                            <div className='col-md-2 col-2 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className='col-md-12 mt-2 pe-md-5'>
                                                        <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                            Culture: A Foundation for Success</p>
                                                        <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                            about working at your company is? Depending on
                                                            where you work, there are a few possible reasons.</p>
                                                    </div>
                                                    <div className='col-md-12'>
                                                        <img className='img-fluid' src='/imagess/readmore.webp' />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className='col-md-6 mt-4 '>
                                                <div className='col-md-12 px-md-3'>
                                                    <div className='col-md-12 '>
                                                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                                        <div className='row px-4 neg_mar_top'>
                                                            <div className='col-md-6 col-6'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                            </div>
                                                            <div className='col-md-4 col-4 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                            </div>
                                                            <div className='col-md-2 col-2 text-end'>
                                                                <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className='col-md-12 mt-2 pe-md-5'>
                                                        <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                            Culture: A Foundation for Success</p>
                                                        <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                            about working at your company is? Depending on
                                                            where you work, there are a few possible reasons.</p>
                                                    </div>
                                                    <div className='col-md-12'>
                                                        <img className='img-fluid' src='/imagess/readmore.webp' />
                                                    </div>
                                                </div>
                                            </div>


                                        </div>
                                        <div className='col-md-12 px-3 mt-5 ' >
                                            <div className='row'>
                                                <div className='col-md-6 pt-3'>
                                                    <p className='showinggg'>Showing: <span className='new_text'>14 of 20</span></p>
                                                </div>
                                                <div className='col-md-6 text-end'>
                                                    <img className='img-fluid' src='/imagess/pg.webp' />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-4 mt-5'>
                                    <div className='col-md-12'>
                                        <p className='m-0 p-0 follow_j'>Follow our journey</p>
                                    </div>
                                    <div className='d-flex mt-3' >
                                        <img className='img-fluid' src='/imagess/facebook.webp' />
                                        <img className='img-fluid ps-3' src='/imagess/twitter.webp' />
                                        <img className='img-fluid ps-3' src='/imagess/instagram.webp' />
                                        <img className='img-fluid ps-3' src='/imagess/pint.webp' />
                                    </div>
                                    <div className='col-md-12 mt-5'>
                                        <p className='m-0 p-0 follow_j'>Popular Blogs</p>
                                    </div>
                                    <div className='col-md-12 mt-3'>
                                        <div className='row'>
                                            <div className='col-md-6'>
                                                <img className='img-fluid w-100' src='/imagess/bb.webp' />
                                            </div>
                                            <div className='col-md-6 m-auto'>
                                                <p className='m-0 p-0 bb_text'>Building a Positive
                                                    Workplace Culture: A
                                                    Foundation for Success</p>
                                                <p className='m-0 p-0 bb_text_Date'>Building a Positive
                                                    2nd feb, 2023
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div className='col-md-12 mt-3'>
                                        <div className='row'>
                                            <div className='col-md-6'>
                                                <img className='img-fluid w-100' src='/imagess/bb.webp' />
                                            </div>
                                            <div className='col-md-6 m-auto'>
                                                <p className='m-0 p-0 bb_text'>Building a Positive
                                                    Workplace Culture: A
                                                    Foundation for Success</p>
                                                <p className='m-0 p-0 bb_text_Date'>Building a Positive
                                                    2nd feb, 2023
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div className='col-md-12 mt-3'>
                                        <div className='row'>
                                            <div className='col-md-6'>
                                                <img className='img-fluid w-100' src='/imagess/bb.webp' />
                                            </div>
                                            <div className='col-md-6 m-auto'>
                                                <p className='m-0 p-0 bb_text'>Building a Positive
                                                    Workplace Culture: A
                                                    Foundation for Success</p>
                                                <p className='m-0 p-0 bb_text_Date'>Building a Positive
                                                    2nd feb, 2023
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div className='col-md-12 mt-3'>
                                        <div className='row'>
                                            <div className='col-md-6'>
                                                <img className='img-fluid w-100' src='/imagess/bb.webp' />
                                            </div>
                                            <div className='col-md-6 m-auto'>
                                                <p className='m-0 p-0 bb_text'>Building a Positive
                                                    Workplace Culture: A
                                                    Foundation for Success</p>
                                                <p className='m-0 p-0 bb_text_Date'>Building a Positive
                                                    2nd feb, 2023
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div className='col-md-12 mt-5'>
                                        <p className='m-0 p-0 follow_j'>Tags</p>
                                    </div>
                                    <div className='col-md-12 '>
                                        <span><button className='btn btn-primary px-5 py-1 mt-2  button_backgroynd_n'>All</button></span>
                                        <span><button className='btn btn-light px-5 py-1 mt-2 ms-2 button_backgroynd_nn'>Business</button></span>
                                        <span><button className='btn btn-light px-5 py-1 mt-2  button_backgroynd_nn'>YAFPAY Guide</button></span>
                                        <span><button className='btn btn-light px-5 py-1 mt-2 ms-2 button_backgroynd_nn'>Information</button></span>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                            <div className='row universal_padding'>
                                <div className='col-md-6 px-md-4'>
                                    <img className='img-fluid' src='/imagess/b4.webp' data-aos="fade-right" data-aos-duration="6000" />
                                </div>
                                <div className='col-md-6 m-auto'>
                                    <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                        Download our App to get all kinds of
                                        banking benefits from anywhere
                                    </p>
                                    <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                        <img className='img-fluid width_gp' src='/imagess/googleplay.webp' />
                                        <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.webp' />
                                    </div>
                                </div>

                            </div>


                        </div>
                        <Footer />
                    </div>
                </LoaderUniversal>
            </main>
        </>
    )
}

export default Blogs