import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import { LuDot } from 'react-icons/lu'
import MobileHeader from '@/Components/MobileHeader/MobileHeader'

function Blogsdetail() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LoaderUniversal>
                    <LanguageHeader />
                    <div className='col-md-12 background_color_universal'>
                        <div className='col-md-12 background_headerpp universal_padding'>
                            <div className='row display_pc pt-4'>
                                <div className='col-md-2 col-5'>
                                    <Link href="/" className='link_style'>
                                        <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2'>
                                    <Link href="/" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Home</p>
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2' >
                                    <Link href="/Blogs" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Blog</p>
                                    </Link>
                                </div>
                               <div className='col-md-1 pt-2 col-3'>
                                    <Link href="/helpcenter" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Help Center</p>
                                    </Link>
                                </div>

                            </div>
                            <div className='display_mob'>
                                <MobileHeader />
                            </div>
                            <div className='col-md-12 mt-5 pb-5'>
                                <div className='row' >
                                    <div className='col-md-6 m-auto '>
                                        <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                            YAFPAY Blogs
                                        </p>
                                        <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                            <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> YAFPAY Blogs</span>
                                        </p>
                                        <div className='col-md-7 mt-5'>
                                            <input className='form-control form-control-lg  search_article' type='text' placeholder='Search an article' />
                                        </div>
                                    </div>

                                    <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                        <img className='img-fluid' data-aos="zoom-in" src='/imagess/contact.webp' />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className='col-md-12 universal_padding text-center'>
                            <p className='font_GBP m-0 p-0' data-aos="zoom-in-up" data-aos-duration="4000">Mastering the Art of Multidisciplinary Creativity:<br />
                                An Interview with Lex Ash</p>
                            <img className='img-fluid mt-4' src='/imagess/mmm.webp' />
                        </div>

                        <div className='col-md-12 universal_padding mt-5'>
                            <p className='m-0 p-0 head_name'>Who is Lex Ash?</p>
                            <p className='m-0 p-0 head_name_p'>
                                Alexandre Chidiebere Ashimole is the full name. The Lex and Ash come from the first name Alexandre and Ash the surname Ashimole.
                                I’ve been creating as far back as I can remember. But I think much of my life has been me learning, discovering new things, and applying it to everything I do. So, if I were to describe myself, I’d be a
                                lifelong learner.
                            </p>
                        </div>

                        <div className='col-md-12 universal_padding mt-5'>
                            <p className='m-0 p-0 head_name'>Who is Lex Ash?</p>
                            <p className='m-0 p-0 head_name_p'>
                                Alexandre Chidiebere Ashimole is the full name. The Lex and Ash come from the first name Alexandre and Ash the surname Ashimole.
                                I’ve been creating as far back as I can remember. But I think much of my life has been me learning, discovering new things, and applying it to everything I do. So, if I were to describe myself, I’d be a
                                lifelong learner.
                            </p>
                        </div>

                        <div className='col-md-12 universal_padding mt-5'>
                            <p className='m-0 p-0 head_name'>Who is Lex Ash?</p>
                            <p className='m-0 p-0 head_name_p'>
                                Alexandre Chidiebere Ashimole is the full name. The Lex and Ash come from the first name Alexandre and Ash the surname Ashimole.
                                I’ve been creating as far back as I can remember. But I think much of my life has been me learning, discovering new things, and applying it to everything I do. So, if I were to describe myself, I’d be a
                                lifelong learner.
                            </p>
                        </div>

                        <div className='col-md-12 universal_padding mt-5'>
                            <p className='m-0 p-0 head_name'>Who is Lex Ash?</p>
                            <p className='m-0 p-0 head_name_p'>
                                Alexandre Chidiebere Ashimole is the full name. The Lex and Ash come from the first name Alexandre and Ash the surname Ashimole.
                                I’ve been creating as far back as I can remember. But I think much of my life has been me learning, discovering new things, and applying it to everything I do. So, if I were to describe myself, I’d be a
                                lifelong learner.
                            </p>
                        </div>

                        <div className='col-md-12 universal_padding mt-5'>
                            <hr />
                        </div>
                        <div className='col-md-12 universal_padding text-center mt-5'>
                            <img className='img-fluid' src='/imagess/ppp.webp' />
                            <p className='m-0 p-0 text_h1'>Haylie Donin</p>
                            <p className='m-0 p-0 text_h2'>Marketing Manager at Bankio</p>
                            <p className='m-0 p-0 text_h3'>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel,<br />
                                viverra facilisi neque quisque.
                            </p>
                            <p className='m-0 p-0 text_h4'>2nd Feb, 2023</p>
                        </div>

                        <div className='col-md-12 universal_padding mt-5  mb-5'>
                            <p className='m-0 p-0 ps-md-3 ppp_text'>Popular Blogs</p>
                            <div className='row'>
                                <div className='col-md-4 mt-4 '>
                                    <div className='col-md-12 px-md-3'>
                                        <div className='col-md-12 '>
                                            <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                            <div className='row px-4 neg_mar_top'>
                                                <div className='col-md-6 col-6'>
                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                </div>
                                                <div className='col-md-4 col-4 text-end'>
                                                    <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                </div>
                                                <div className='col-md-2 col-2 text-end'>
                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-12 mt-2 pe-md-5'>
                                            <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                Culture: A Foundation for Success</p>
                                            <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                about working at your company is? Depending on
                                                where you work, there are a few possible reasons.</p>
                                        </div>
                                        <div className='col-md-12'>
                                            <img className='img-fluid' src='/imagess/readmore.webp' />
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-4 mt-4 '>
                                    <div className='col-md-12 px-md-3'>
                                        <div className='col-md-12 '>
                                            <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                            <div className='row px-4 neg_mar_top'>
                                                <div className='col-md-6 col-6'>
                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                </div>
                                                <div className='col-md-4 col-4 text-end'>
                                                    <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                </div>
                                                <div className='col-md-2 col-2 text-end'>
                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-12 mt-2 pe-md-5'>
                                            <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                Culture: A Foundation for Success</p>
                                            <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                about working at your company is? Depending on
                                                where you work, there are a few possible reasons.</p>
                                        </div>
                                        <div className='col-md-12'>
                                            <img className='img-fluid' src='/imagess/readmore.webp' />
                                        </div>
                                    </div>
                                </div>
                                <div className='col-md-4 mt-4 '>
                                    <div className='col-md-12 px-md-3'>
                                        <div className='col-md-12 '>
                                            <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                                            <div className='row px-4 neg_mar_top'>
                                                <div className='col-md-6 col-6'>
                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                                                </div>
                                                <div className='col-md-4 col-4 text-end'>
                                                    <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                                                </div>
                                                <div className='col-md-2 col-2 text-end'>
                                                    <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-12 mt-2 pe-md-5'>
                                            <p className='m-0 p-0 font_cards pe-md-5'>Building a Positive Workplace
                                                Culture: A Foundation for Success</p>
                                            <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                about working at your company is? Depending on
                                                where you work, there are a few possible reasons.</p>
                                        </div>
                                        <div className='col-md-12'>
                                            <img className='img-fluid' src='/imagess/readmore.webp' />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                            <div className='row universal_padding'>
                                <div className='col-md-6 px-md-4'>
                                    <img className='img-fluid' src='/imagess/b4.webp' data-aos="fade-right" data-aos-duration="6000" />
                                </div>
                                <div className='col-md-6 m-auto'>
                                    <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                        Download our App to get all kinds of
                                        banking benefits from anywhere
                                    </p>
                                    <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                        <img className='img-fluid width_gp' src='/imagess/googleplay.webp' />
                                        <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.webp' />
                                    </div>
                                </div>

                            </div>


                        </div>
                        <Footer />
                    </div>
                </LoaderUniversal>
            </main >
        </>
    )
}

export default Blogsdetail