import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect, useState } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import { LuDot } from 'react-icons/lu'
import Button from 'react-bootstrap/Button';
import Collapse from 'react-bootstrap/Collapse';
import MobileHeader from '@/Components/MobileHeader/MobileHeader'

function Contactus() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);

    const [open1, setOpen1] = useState(false);
    const [open2, setOpen2] = useState(false);
    const [open3, setOpen3] = useState(false);
    const [open4, setOpen4] = useState(false);
    const [open5, setOpen5] = useState(false);
    const [open6, setOpen6] = useState(false);
    return (
        <>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LoaderUniversal>
                    <LanguageHeader />
                    <div className='col-md-12 background_color_universal'>
                        <div className='col-md-12 background_headerpp universal_padding'>
                            <div className='row display_pc pt-4'>
                                <div className='col-md-2 col-5'>
                                    <Link href="/" className='link_style'>
                                        <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2'>
                                    <Link href="/" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Home</p>
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2' >
                                    <Link href="/Blogs" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Blog</p>
                                    </Link>
                                </div>
                               <div className='col-md-1 pt-2 col-3'>
                                    <Link href="/helpcenter" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Help Center</p>
                                    </Link>
                                </div>

                            </div>
                            <div className='display_mob'>
                                <MobileHeader />
                            </div>
                            <div className='col-md-12 mt-5 pb-5'>
                                <div className='row'>
                                    <div className='col-md-6 m-auto '>
                                        <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                            Contact Us
                                        </p>
                                        <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                            <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> Contact Us</span>
                                        </p>
                                    </div>
                                    <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                        <img className='img-fluid' data-aos="zoom-in" src='/imagess/contact.webp' />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className='col-md-12  background_header2 pt-5 mt-5 '>
                            <div className='col-md-12  text-center'>
                                <p className='font_GBP m-0 p-0' data-aos="zoom-in-up" data-aos-duration="4000">Need More Help?</p>
                                <p className='font_GBP1' data-aos="zoom-in-up" data-aos-duration="4000">Queries, complaints and feedback. We will be happy to serve you</p>
                            </div>
                            <div className='col-md-12 universal_padding_left'>
                                <div className='row mt-5 pt-4  pb-5' >
                                    <div className='col-md-6 m-auto'>
                                        <div className='col-md-12 '>
                                            <img className='img-fluid' src='/imagess/heart.webp' data-aos="fade-right" data-aos-duration="4000" />
                                            <p className='m-0 p-0 heading_b2' data-aos="fade-right" data-aos-duration="3000">Sales</p>
                                            <p className='m-0 p-0 sub_heading_b2' data-aos="fade-right" data-aos-duration="3000">
                                                sales@yafpay.com
                                            </p>
                                        </div>
                                        <div className='col-md-12 mt-5'>
                                            <img className='img-fluid' src='/imagess/head.webp' data-aos="fade-right" data-aos-duration="4000" />
                                            <p className='m-0 p-0 heading_b2' data-aos="fade-right" data-aos-duration="3000">Help & Support</p>
                                            <p className='m-0 p-0 sub_heading_b2' data-aos="fade-right" data-aos-duration="3000">
                                                supports@yafpay.com
                                            </p>
                                        </div>
                                        <div className='col-md-12 mt-5 mb-5'>
                                            <img className='img-fluid' src='/imagess/paper.webp' data-aos="fade-right" data-aos-duration="4000" />
                                            <p className='m-0 p-0 heading_b2' data-aos="fade-right" data-aos-duration="3000">Media & Press</p>
                                            <p className='m-0 p-0 sub_heading_b2' data-aos="fade-right" data-aos-duration="3000">
                                                Mediapress@yafpay.com
                                            </p>
                                        </div>
                                    </div>
                                    <div className='col-md-6 text-end mt-5 mt-md-0'>
                                        <img className='img-fluid' src='/imagess/csv.webp' data-aos="fade-left" data-aos-duration="4000" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div className='col-md-12 background_blue py-5  universal_padding' >
                            <p className='m-0 p-0 text_banner4' data-aos="zoom-in-up" data-aos-duration="4000">Get in touch with us.</p>
                            <div className='row mt-3 px-3 px-md-0'>
                                <div className='row'>
                                    <div className='col-md-6 mt-4'>
                                        <div className='col-md-12 px-3'>
                                            <input className='form-control' type='text' placeholder='Name' />
                                        </div>
                                    </div>
                                    <div className='col-md-6 mt-4'>
                                        <div className='col-md-12 px-3'>
                                            <input className='form-control' type='email' placeholder='Email' />
                                        </div>
                                    </div>
                                    <div className='col-md-6 mt-4'>
                                        <div className='col-md-12 px-3'>
                                            <input className='form-control' type='phone' placeholder='Phone Number' />
                                        </div>
                                    </div>
                                    <div className='col-md-6 mt-4'>
                                        <div className='col-md-12 px-3'>
                                            <input className='form-control' type='text' placeholder='Interested Service (payment link etc)' />
                                        </div>
                                    </div>
                                    <div className='col-md-12 mt-4'>
                                        <div className='col-md-12 px-3'>
                                            <textarea className='form-control' type='text' placeholder='Massage' />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className='col-md-12 mt-5 px-2 px-md-0 text-center'>
                                <img className='img-fluid' data-aos="fade-right" data-aos-duration="3000" src='/imagess/submit.webp' />
                            </div>
                        </div>
                        <div className='col-md-12  background_header22 pt-5 mb-5 pb-5 '>
                            <div className='row universal_padding'>
                                <div className='col-md-12  text-center mb-5 '>
                                    <p className='font_GBP mb-0' data-aos="zoom-in-up" data-aos-duration="4000">Frequently ask question</p>
                                    <p className='font_GBP1' data-aos="zoom-in-up" data-aos-duration="4000">Just find your answers below</p>
                                </div>
                                <div className='col-md-4'>
                                    <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/banner-s3.webp' />
                                </div>
                                <div className='col-md-8 px-md-5 mt-5 m-md-auto'>
                                    <div className='col-md-12 background_card_new11   bg-white'
                                        onClick={() => setOpen1(!open1)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open1}
                                    >
                                        <div className={`col-md-12 ${open1 ? "background_active_drop" : ""} py-2 px-3`}>
                                            <div className='row'>
                                                <div className='col-md-8 col-10 m-auto'>
                                                    <p className='m-0 p-0 new_c_text'>1. What kind of financial consultancy you need?</p>
                                                </div>
                                                <div className='col-md-4 col-2 text-end'>
                                                    <img className='img-fluid' src={`/imagess/${open1 ? "minus" : "pluss"}.webp`} />
                                                </div>
                                            </div>
                                        </div>
                                        <Collapse in={open1} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen2(!open2)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open2}
                                    >
                                        <div className={`col-md-12 ${open2 ? "background_active_drop" : ""} py-2 px-3`}>
                                            <div className='row'>
                                                <div className='col-md-8 col-10 m-auto'>
                                                    <p className='m-0 p-0 new_c_text'>2. What Is The Best Features And Services We Deliver?</p>
                                                </div>
                                                <div className='col-md-4 col-2 text-end'>
                                                    <img className='img-fluid' src={`/imagess/${open2 ? "minus" : "pluss"}.webp`} />
                                                </div>
                                            </div>
                                        </div>
                                        <Collapse in={open2} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen3(!open3)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open3}
                                    >
                                        <div className={`col-md-12 ${open3 ? "background_active_drop" : ""} py-2 px-3`}>
                                            <div className='row'>
                                                <div className='col-md-8 col-10 m-auto'>
                                                    <p className='m-0 p-0 new_c_text'>3. What Are The Objectives Of This Service?</p>
                                                </div>
                                                <div className='col-md-4 col-2 text-end'>
                                                    <img className='img-fluid' src={`/imagess/${open3 ? "minus" : "pluss"}.webp`} />
                                                </div>
                                            </div>
                                        </div>
                                        <Collapse in={open3} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen4(!open4)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open4}
                                    >
                                        <div className={`col-md-12 ${open4 ? "background_active_drop" : ""} py-2 px-3`}>
                                            <div className='row'>
                                                <div className='col-md-8 col-10 m-auto'>
                                                    <p className='m-0 p-0 new_c_text'>4. What Is A Multi-currency Card?</p>
                                                </div>
                                                <div className='col-md-4 col-2 text-end'>
                                                    <img className='img-fluid' src={`/imagess/${open4 ? "minus" : "pluss"}.webp`} />
                                                </div>
                                            </div>
                                        </div>
                                        <Collapse in={open4} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen5(!open5)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open5}
                                    >
                                        <div className={`col-md-12 ${open5 ? "background_active_drop" : ""} py-2 px-3`}>
                                            <div className='row'>
                                                <div className='col-md-8 col-10 m-auto'>
                                                    <p className='m-0 p-0 new_c_text'>5. What Is The Best Features And Services We Deliver?</p>
                                                </div>
                                                <div className='col-md-4 col-2 text-end'>
                                                    <img className='img-fluid' src={`/imagess/${open5 ? "minus" : "pluss"}.webp`} />
                                                </div>
                                            </div>
                                        </div>
                                        <Collapse in={open5} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>
                                    <div className='col-md-12 background_card_new11 mt-4   bg-white'
                                        onClick={() => setOpen6(!open6)}
                                        aria-controls="example-collapse-text"
                                        aria-expanded={open6}
                                    >
                                        <div className={`col-md-12 ${open6 ? "background_active_drop" : ""} py-2 px-3`}>
                                            <div className='row'>
                                                <div className='col-md-8 col-10 m-auto'>
                                                    <p className='m-0 p-0 new_c_text'>6. What Happened To The Borderless Account?</p>
                                                </div>
                                                <div className='col-md-4 col-2 text-end'>
                                                    <img className='img-fluid' src={`/imagess/${open6 ? "minus" : "pluss"}.webp`} />
                                                </div>
                                            </div>
                                        </div>
                                        <Collapse in={open6} className='mt-2 px-3'>
                                            <div id="example-collapse-text ">
                                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                                                terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                                                labore wes anderson cred nesciunt sapiente ea proident.
                                            </div>
                                        </Collapse>
                                    </div>

                                </div>
                            </div>


                        </div>
                        <Footer />
                    </div>
                </LoaderUniversal>
            </main>
        </>
    )
}

export default Contactus