import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import { LuDot } from 'react-icons/lu'

function helpcenter() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LoaderUniversal>
                    <LanguageHeader />
                    <div className='col-md-12 background_color_universal'>
                        <div className='col-md-12 background_headerpp universal_padding'>
                            <div className='row pt-4'>
                                <div className='col-md-2 col-5'>
                                    <Link href="/">
                                        <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                                    </Link>
                                </div>
                                <div className='col-md-1 pt-2 col-2'>
                                    <p className='m-0 p-0 font_header2'>Home</p>
                                </div>
                                <div className='col-md-1 pt-2 col-2' >
                                    <p className='m-0 p-0 font_header2'>Blog</p>
                                </div>
                               <div className='col-md-1 pt-2 col-3'>
                                    <Link href="/helpcenter" className='link_style'>
                                        <p className='m-0 p-0 font_header2'>Help Center</p>
                                    </Link>
                                </div>

                            </div>
                            <div className='col-md-12 mt-5 pb-5'>
                                <div className='row'>
                                    <div className='col-md-6 m-auto '>
                                        <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                            Help Centre
                                        </p>
                                        <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                            <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> Help Centre</span>
                                        </p>
                                        <div className='col-md-7 mt-5'>
                                            <input className='form-control form-control-lg  search_article' type='text' placeholder='Search an article' />
                                        </div>
                                    </div>

                                    <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                        <img className='img-fluid' data-aos="zoom-in" src='/imagess/lady.png' />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col-md-12 universal_padding'>
                            <div className='col-md-12'>
                                <div className='col-md-12 mb-5'>
                                    <div className='row'>
                                        <div className='col-md-4 mt-4 '>
                                            <div className='col-md-12 px-md-3'>
                                                <div className='col-md-12 '>
                                                    <img className='img-fluid w-100' src='/imagess/h1.png' />
                                                    <div className='row px-4 neg_mar_top'>
                                                        <div className='col-md-6 col-6'>
                                                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> 1 Author</p>
                                                        </div>
                                                        <div className='col-md-6 col-6 text-end'>
                                                            <p className='m-0 p-0 font_in_cards'>5 Articals</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-12 mt-2 pe-md-5'>
                                                    <p className='m-0 p-0 font_cards pe-md-5'>Getting Started</p>
                                                    <p className='m-0 p-0 font_cards_para pe-md-5'>
                                                        Have you ever been asked what your favorite thing
                                                        about working at your company is? Depending on
                                                        where you work, there are a few possible reasons.
                                                    </p>
                                                </div>
                                                <div className='col-md-12'>
                                                    <img className='img-fluid' src='/imagess/readmore.webp' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-4 mt-4 '>
                                            <div className='col-md-12 px-md-3'>
                                                <div className='col-md-12 '>
                                                    <img className='img-fluid w-100' src='/imagess/h2.png' />
                                                    <div className='row px-4 neg_mar_top'>
                                                        <div className='col-md-6 col-6'>
                                                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> 1 Author</p>
                                                        </div>
                                                        <div className='col-md-6 col-6 text-end'>
                                                            <p className='m-0 p-0 font_in_cards'>5 Articals</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-12 mt-2 pe-md-5'>
                                                    <p className='m-0 p-0 font_cards pe-md-5'>Receiving Amount</p>
                                                    <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                        about working at your company is? Depending on
                                                        where you work, there are a few possible reasons.</p>
                                                </div>
                                                <div className='col-md-12'>
                                                    <img className='img-fluid' src='/imagess/readmore.webp' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-4 mt-4 '>
                                            <div className='col-md-12 px-md-3'>
                                                <div className='col-md-12 '>
                                                    <img className='img-fluid w-100' src='/imagess/h3.png' />
                                                    <div className='row px-4 neg_mar_top'>
                                                        <div className='col-md-6 col-6'>
                                                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> 1 Author</p>
                                                        </div>
                                                        <div className='col-md-6 col-6 text-end'>
                                                            <p className='m-0 p-0 font_in_cards'>5 Articals</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-12 mt-2 pe-md-5'>
                                                    <p className='m-0 p-0 font_cards pe-md-5'>Send Money</p>
                                                    <p className='m-0 p-0 font_cards_para pe-md-5'>Have you ever been asked what your favorite thing
                                                        about working at your company is? Depending on
                                                        where you work, there are a few possible reasons.</p>
                                                </div>
                                                <div className='col-md-12'>
                                                    <img className='img-fluid' src='/imagess/readmore.webp' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-4 mt-4 '>
                                            <div className='col-md-12 px-md-3'>
                                                <div className='col-md-12 '>
                                                    <img className='img-fluid w-100' src='/imagess/h4.png' />
                                                    <div className='row px-4 neg_mar_top'>
                                                        <div className='col-md-6 col-6'>
                                                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> 1 Author</p>
                                                        </div>
                                                        <div className='col-md-6 col-6 text-end'>
                                                            <p className='m-0 p-0 font_in_cards'>5 Articals</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-12 mt-2 pe-md-5'>
                                                    <p className='m-0 p-0 font_cards pe-md-5'>YAFPAY Virtual Card</p>
                                                    <p className='m-0 p-0 font_cards_para pe-md-5'>
                                                        Have you ever been asked what your favorite thing
                                                        about working at your company is? Depending on
                                                        where you work, there are a few possible reasons.
                                                    </p>
                                                </div>
                                                <div className='col-md-12'>
                                                    <img className='img-fluid' src='/imagess/readmore.webp' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-4 mt-4 '>
                                            <div className='col-md-12 px-md-3'>
                                                <div className='col-md-12 '>
                                                    <img className='img-fluid w-100' src='/imagess/h5.png' />
                                                    <div className='row px-4 neg_mar_top'>
                                                        <div className='col-md-6 col-6'>
                                                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> 1 Author</p>
                                                        </div>
                                                        <div className='col-md-6 col-6 text-end'>
                                                            <p className='m-0 p-0 font_in_cards'>5 Articals</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-12 mt-2 pe-md-5'>
                                                    <p className='m-0 p-0 font_cards pe-md-5'>
                                                        Airtime, Data and Bills Payments
                                                    </p>
                                                    <p className='m-0 p-0 font_cards_para pe-md-5'>
                                                        Have you ever been asked what your favorite thing
                                                        about working at your company is? Depending on
                                                        where you work, there are a few possible reasons.
                                                    </p>
                                                </div>
                                                <div className='col-md-12'>
                                                    <img className='img-fluid' src='/imagess/readmore.webp' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className='col-md-4 mt-4 '>
                                            <div className='col-md-12 px-md-3'>
                                                <div className='col-md-12 '>
                                                    <img className='img-fluid w-100' src='/imagess/h6.png' />
                                                    <div className='row px-4 neg_mar_top'>
                                                        <div className='col-md-6 col-6'>
                                                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> 1 Author</p>
                                                        </div>
                                                        <div className='col-md-6 col-6 text-end'>
                                                            <p className='m-0 p-0 font_in_cards'>5 Articals</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className='col-md-12 mt-2 pe-md-5'>
                                                    <p className='m-0 p-0 font_cards pe-md-5'>
                                                        Invoices
                                                    </p>
                                                    <p className='m-0 p-0 font_cards_para pe-md-5'>
                                                        Have you ever been asked what your favorite thing
                                                        about working at your company is? Depending on
                                                        where you work, there are a few possible reasons.
                                                    </p>
                                                </div>
                                                <div className='col-md-12'>
                                                    <img className='img-fluid' src='/imagess/readmore.webp' />
                                                </div>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>

                        <Footer />
                    </div>
                </LoaderUniversal>
            </main>
        </>
    )
}

export default helpcenter