import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import MobileHeader from '@/Components/MobileHeader/MobileHeader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    setTimeout(function () {
    }, 6000);
    Aos.init({
      duration: 2000,
      easing: 'ease',
    });
  }, []);


  return (
    <>
      <Head>
        <title>YafPay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <LoaderUniversal>
          <LanguageHeader />
          <div className='col-md-12 background_color_universal'>
            <div className='col-md-12 background_header1 universal_padding'>
              <div className='row pt-4 display_pc'>
                <div className='col-md-2 col-5'>
                  <Link href="/" className='link_style'>
                    <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                  </Link>
                </div>
                <div className='col-md-1 pt-2 col-2'>
                  <Link href="/" className='link_style'>
                    <p className='m-0 p-0 font_header2'>Home</p>
                  </Link>
                </div>
                <div className='col-md-1 pt-2 col-2' >
                  <Link href="/Blogs" className='link_style'>
                    <p className='m-0 p-0 font_header2'>Blog</p>
                  </Link>
                </div>
                <div className='col-md-1 pt-2 col-3'>
                  <Link href="/helpcenter" className='link_style'>
                    <p className='m-0 p-0 font_header2'>Help Center</p>
                  </Link>
                </div>

              </div>
              <div className='display_mob'>
                <MobileHeader />
              </div>
              <div className='col-md-12 mt-5 pb-5'>
                <div className='row'>
                  <div className='col-md-6 m-auto '>
                    <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                      The future of digital
                      money transfer
                    </p>
                    <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                      Open a U.S., U.K. and European bank account for free to receive and make
                      foreign <br /> payments or convert currencies, all in one place
                    </p>
                    <div className='col-md-12 mt-md-5 pt-4'>
                      <img className='img-fluid width_gp' src='/imagess/googleplay.webp' data-aos="fade-right" data-aos-duration="4000" />
                      <img className='img-fluid ps-md-4 ps-2 width_gp' src='/imagess/apple.webp' data-aos="fade-right" data-aos-duration="3000" />
                    </div>
                    <div className='col-md-12 mt-md-3 mt-4'>
                      <div className='row'>
                        <div className='col-md-3 col-4 '>
                          <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/people.webp' />
                        </div>
                        <div className='col-md-9 col-8 m-auto'>
                          <p className='m-0 p-0' data-aos="fade-left" data-aos-duration="3000"><span className='fivek'>500K+</span><span className='people ps-2'>People already trusted us.</span></p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className='col-md-6 mt-md-0 mt-5 text-center'>
                    <img className='img-fluid' data-aos="zoom-in" src='/imagess/banner1.webp' />
                  </div>
                </div>
              </div>
            </div>

            <div className='col-md-12  background_header2 pt-5 mt-5 '>
              <div className='col-md-12  text-center'>
                <p className='font_GBP' data-aos="zoom-in-up" data-aos-duration="4000">
                  Free USD, GBP and EUR accounts<br />
                  for all your international transactions</p>
              </div>
              <div className='col-md-12 universal_padding_left'>
                <div className='row mt-5 pt-4  pb-5' >
                  <div className='col-md-6'>
                    <div className='col-md-12 '>
                      <img className='img-fluid' src='/imagess/ico1.webp' data-aos="fade-right" data-aos-duration="4000" />
                      <p className='m-0 p-0 heading_b2' data-aos="fade-right" data-aos-duration="3000">Send and receive money quickly</p>
                      <p className='m-0 p-0 sub_heading_b2' data-aos="fade-right" data-aos-duration="3000">
                        Enjoy fast global money transfer with your international bank<br />
                        account on YAFPAY.
                      </p>
                      <img className='img-fluid mt-3' src='/imagess/start.webp' data-aos="fade-right" data-aos-duration="4000" />
                    </div>
                    <div className='col-md-12 mt-3'>
                      <img className='img-fluid' src='/imagess/ico2.webp' data-aos="fade-right" data-aos-duration="4000" />
                      <p className='m-0 p-0 heading_b2' data-aos="fade-right" data-aos-duration="3000">Instant currency exchange</p>
                      <p className='m-0 p-0 sub_heading_b2' data-aos="fade-right" data-aos-duration="3000">
                        Enjoy quick and efficient online foreign exchange transactions.<br />
                        Say goodbye to bank queues and disappointments..
                      </p>
                      <img className='img-fluid mt-3' src='/imagess/start.webp' data-aos="fade-right" data-aos-duration="4000" />
                    </div>
                    <div className='col-md-12 mt-3 mb-5'>
                      <img className='img-fluid' src='/imagess/ico3.webp' data-aos="fade-right" data-aos-duration="4000" />
                      <p className='m-0 p-0 heading_b2' data-aos="fade-right" data-aos-duration="3000">Send and receive money quickly</p>
                      <p className='m-0 p-0 sub_heading_b2' data-aos="fade-right" data-aos-duration="3000">
                        Enjoy fast global money transfer with your international bank<br />
                        account on YAFPAY.
                      </p>
                      <img className='img-fluid mt-3' src='/imagess/start.webp' data-aos="fade-right" data-aos-duration="4000" />
                    </div>
                  </div>
                  <div className='col-md-6 text-end mt-5 mt-md-0'>
                    <img className='img-fluid' src='/imagess/banner2.webp' data-aos="fade-left" data-aos-duration="4000" />
                  </div>
                </div>
              </div>

            </div>
            <div className='col-md-12 background_blue py-5  universal_padding' >
              <p className='m-0 p-0 text_banner4' data-aos="zoom-in-up" data-aos-duration="4000">How to open a free foreign bank account</p>
              <div className='row mt-5 px-3 px-md-0'>
                <div className='col-md-4 mt-md-0 mt-3'>
                  <div className='row'>
                    <div className='col-md-1 col-1 px-0'>
                      <img className='img-fluid'
                        data-aos="fade-right" data-aos-duration="4000"
                        src='/imagess/one.webp' />
                    </div>
                    <div className='col-md-11 col-11'>
                      <p className='m-0 p-0 register_text' data-aos="fade-right" data-aos-duration="4000" >Register in minutes</p>
                      <p className='m-0 p-0 reg_text_1' data-aos="fade-right" data-aos-duration="3000" >
                        Sign up online, or in our app with your<br />
                        email address
                      </p>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 mt-3'>
                  <div className='row'>
                    <div className='col-md-1 col-1 px-0'>
                      <img className='img-fluid'
                        data-aos="fade-right" data-aos-duration="4000"
                        src='/imagess/one.webp' />
                    </div>
                    <div className='col-md-11 col-11'>
                      <p className='m-0 p-0 register_text' data-aos="fade-right" data-aos-duration="4000" >Complete KYC verifications</p>
                      <p className='m-0 p-0 reg_text_1' data-aos="fade-right" data-aos-duration="3000" >
                        Verify your identity using your government-<br />
                        issued ID
                      </p>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 mt-3'>
                  <div className='row'>
                    <div className='col-md-1 col-1 px-0'>
                      <img className='img-fluid'
                        data-aos="fade-right" data-aos-duration="4000"
                        src='/imagess/one.webp' />
                    </div>
                    <div className='col-md-11 col-11'>
                      <p className='m-0 p-0 register_text' data-aos="fade-right" data-aos-duration="4000" >Get your virtual account</p>
                      <p className='m-0 p-0 reg_text_1' data-aos="fade-right" data-aos-duration="3000" >
                        Share your account details to get paid, or spend<br />
                        around the world with your debit card.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='col-md-12 mt-5 px-2 px-md-0'>
                <img className='img-fluid' data-aos="fade-right" data-aos-duration="3000" src='/imagess/register.webp' />
              </div>
            </div>
            <div className='col-md-12  background_header3 pt-5  '>
              <div className='row universal_padding'>
                <div className='col-md-6'>
                  <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/cards.webp' />
                </div>
                <div className='col-md-6 m-auto'>
                  <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="4000">We can easily open a YAFPAY account<br />
                    by following some rules below.</p>
                  <div className='col-md-12 px-md-3 px-2 mt-5' >
                    <div className='row'>
                      <div className='col-md-1 col-1 px-0'>
                        <img className='img-fluid' src='/imagess/onee.webp' data-aos="fade-left" data-aos-duration="5000" />
                      </div>
                      <div className='col-md-11 col-11'>
                        <p className='m-0 p-0 sub_head_new' data-aos="fade-left" data-aos-duration="4000">Personal details</p>
                        <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">Start by creating your YafPay account. Enter your name and email to tailor your
                          financial experience.</p>
                      </div>
                    </div>
                    <div className='row mt-3'>
                      <div className='col-md-1 col-1 px-0' data-aos="fade-left" data-aos-duration="5000">
                        <img className='img-fluid' src='/imagess/two.webp' />
                      </div>
                      <div className='col-md-11 col-11'>
                        <p className='m-0 p-0 sub_head_new' data-aos="fade-left" data-aos-duration="4000">Identification</p>
                        <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">Elevate security by verifying your identity. Provide a valid identification document
                          for a protected and compliant environment.</p>
                      </div>
                    </div>
                    <div className='row mt-3'>
                      <div className='col-md-1 col-1 px-0'>
                        <img className='img-fluid' src='/imagess/three.webp' />
                      </div>
                      <div className='col-md-11 col-11' data-aos="fade-left" data-aos-duration="5000">
                        <p className='m-0 p-0 sub_head_new' data-aos="fade-left" data-aos-duration="4000">Address information</p>
                        <p className='m-0 p-0 subb_head' data-aos="fade-left" data-aos-duration="3000">Confirm your address details to add precision to your transactions. Your financial
                          interactions are now set for accuracy and reliability.</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-12 position_new pe-0'>
                  <img className='img-fluid wisth_circle' src='/imagess/side.webp' />
                </div>
              </div>


            </div>
            <div className='col-md-12  background_header3 pt-5  '>
              <div className='row universal_padding'>
                <div className='col-md-6 m-auto'>
                  <p className='text_section6' data-aos="fade-right" data-aos-duration="4000">
                    We operate our banking services in<br /> many countries around the world
                  </p>
                  <div className='col-md-12 px-3 mt-5'>
                    <div className='row mt-3'>
                      <div className='col-md-1 col-1 '>
                        <img className='img-fluid' src='/imagess/check.webp' data-aos="fade-right" data-aos-duration="4000" />
                      </div>
                      <div className='col-md-11 col-11'>
                        <p className='m-0 p-0 subb_head ' data-aos="fade-right" data-aos-duration="3000">
                          We don't lend out your money and we make sure that it's always secure with our institutional partners so you have nothing to worry about.
                        </p>
                      </div>
                    </div>
                    <div className='row mt-3'>
                      <div className='col-md-1 col-1 '>
                        <img className='img-fluid' src='/imagess/check.webp' data-aos="fade-right" data-aos-duration="4000" />
                      </div>
                      <div className='col-md-11 col-11'>
                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000">
                          Our AML and security teams are dedicated to keeping your account safe and protected from fraud at all times.
                        </p>
                      </div>
                    </div>
                    <div className='row mt-3'>
                      <div className='col-md-1 col-1 '>
                        <img className='img-fluid' src='/imagess/check.webp' data-aos="fade-right" data-aos-duration="4000" />
                      </div>
                      <div className='col-md-11 col-11'>
                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000" >
                          We protect your information with us and it's always secure. We collect and use your information fairly, lawfully and transparently.
                        </p>
                      </div>
                    </div>
                    <div className='row mt-3'>
                      <div className='col-md-1 col-1 '>
                        <img className='img-fluid' src='/imagess/check.webp' data-aos="fade-right" data-aos-duration="4000" />
                      </div>
                      <div className='col-md-11 col-11'>
                        <p className='m-0 p-0 subb_head' data-aos="fade-right" data-aos-duration="3000">
                          Your account is protected with 2FA and only you have access to it. Learn how to set up 2- factor authentication here
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-6 text-end mt-5 mt-md-0'>
                  <img className='img-fluid' src='/imagess/mob2.webp' data-aos="fade-left" data-aos-duration="6000" />
                </div>

              </div>


            </div>
            <div className='col-md-12 bg-white pt-5 '>
              <div className='col-md-12 universal_padding mt-5 mb-5 pb-5'>
                <div className='flex_set'>
                  <img className='img-fluid px-md-5 px-2 mt-md-0 mt-4' src='/imagess/mo.webp' />
                  <img className='img-fluid px-md-5 px-2 mt-md-0 mt-4' src='/imagess/db.webp' />
                  <img className='img-fluid px-md-5 px-2 mt-md-0 mt-4' src='/imagess/pd.webp' />
                  <img className='img-fluid px-md-5 px-2 mt-md-0 mt-4' src='/imagess/ft.webp' />
                  <img className='img-fluid px-md-5 px-2 mt-md-0 mt-4' src='/imagess/dm.webp' />
                </div>
              </div>
            </div>
            <div className='col-md-12 background_header_linear_22 mt-5 pt-5'>
              <div className='col-md-12 pb-4  text-center'>
                <p className='font_GBP' data-aos="zoom-in-up" data-aos-duration="4000">
                  Building a Positive Workplace Culture: A Foundation for Success
                </p>
              </div>
              <div className='col-md-12 universal_padding mt-5 mb-5 pb-5'>

                <div className='row'>
                  <div className='col-md-4 mt-4 mt-md-0'>
                    <div className='col-md-12 px-md-3'>
                      <div className='col-md-12 '>
                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                        <div className='row px-4 neg_mar_top'>
                          <div className='col-md-6 col-6'>
                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                          </div>
                          <div className='col-md-4 col-4 text-end'>
                            <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                          </div>
                          <div className='col-md-2 col-2 text-end'>
                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 mt-2 pe-md-5'>
                        <p className='m-0 p-0 font_cards pe-md-5'>Unlock Financial Freedom Today!
                        </p>
                        <p className='m-0 p-0 font_cards_para pe-md-5'>Experience a financial world where simplicity meets power. YafPay opens the
                          door to effortless money management. From smooth transactions to intuitive
                          budgeting, take control of your financial journey. Join us and
                          discover how managing your money can be as easy as a breeze!
                        </p>
                      </div>
                      <div className='col-md-12'>
                        <img className='img-fluid' src='/imagess/readmore.webp' />
                      </div>
                    </div>
                  </div>
                  <div className='col-md-4 mt-4 mt-md-0'>
                    <div className='col-md-12 px-md-3'>
                      <div className='col-md-12 '>
                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                        <div className='row px-4 neg_mar_top'>
                          <div className='col-md-6 col-6'>
                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                          </div>
                          <div className='col-md-4 col-4 text-end'>
                            <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                          </div>
                          <div className='col-md-2 col-2 text-end'>
                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 mt-2 pe-md-5'>
                        <p className='m-0 p-0 font_cards pe-md-5'>Empower Your Finances with YafPay!</p>
                        <p className='m-0 p-0 font_cards_para pe-md-5'>
                          Wave goodbye to complexity and take charge of your financial destiny. YafPay
                          puts the control back in your hands. Navigate your budget, monitor spending, and
                          execute transactions effortlessly.Your financial journey,
                          simplified – that's the essence of YafPay. Ready to experience it yourself?</p>
                      </div>
                      <div className='col-md-12'>
                        <img className='img-fluid' src='/imagess/readmore.webp' />
                      </div>
                    </div>
                  </div>
                  <div className='col-md-4 mt-4 mt-md-0'>
                    <div className='col-md-12 px-md-3'>
                      <div className='col-md-12 '>
                        <img className='img-fluid w-100' src='/imagess/banner-v3.webp' />
                        <div className='row px-4 neg_mar_top'>
                          <div className='col-md-6 col-6'>
                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/profile.webp' /> Muhammad Usman</p>
                          </div>
                          <div className='col-md-4 col-4 text-end'>
                            <p className='m-0 p-0 font_in_cards'>2nd Feb 2023</p>
                          </div>
                          <div className='col-md-2 col-2 text-end'>
                            <p className='m-0 p-0 font_in_cards'><img className='img-fluid' src='/imagess/comments.webp' /> 23</p>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 mt-2 pe-md-5'>
                        <p className='m-0 p-0 font_cards pe-md-5'>Your Personal Finance Oasis!</p>
                        <p className='m-0 p-0 font_cards_para pe-md-5'>
                          Step into a financial sanctuary with YafPay. Our platform is a tailored space
                          designed for your comfort and financial intuition. Explore a world where banking
                          is seamless, secure, and uniquely yours. Read More Join us and transform
                          the way you experience financial management – simplicity at its finest!

                        </p>
                      </div>
                      <div className='col-md-12'>
                        <img className='img-fluid' src='/imagess/readmore.webp' />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
              <div className='row universal_padding'>
                <div className='col-md-6 px-md-4'>
                  <img className='img-fluid' src='/imagess/b4.webp' data-aos="fade-right" data-aos-duration="6000" />
                </div>
                <div className='col-md-6 m-auto'>
                  <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                    Download our App to get all kinds of
                    banking benefits from anywhere
                  </p>
                  <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                    <img className='img-fluid width_gp' src='/imagess/googleplay.webp' />
                    <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.webp' />
                  </div>
                </div>

              </div>


            </div>
            <Footer />
          </div>
        </LoaderUniversal>
      </main>
    </>
  )
}
