import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import { LuDot } from "react-icons/lu";
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'

function Privacypolicy() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <LoaderUniversal>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LanguageHeader />
                <div className='col-md-12 background_color_universal'>
                    <div className='col-md-12 background_headerpp universal_padding'>
                        <div className='row pt-4'>
                            <div className='col-md-2 col-5'>
                                <Link href="/">
                                    <img className='img-fluid width_gp_l' src='/imagess/logo.png' />
                                </Link>
                            </div>
                            <div className='col-md-1 pt-2 col-2'>
                                <p className='m-0 p-0 font_header2'>Home</p>
                            </div>
                            <div className='col-md-1 pt-2 col-2' >
                                <p className='m-0 p-0 font_header2'>Blog</p>
                            </div>
                            <div className='col-md-1 pt-2 col-3'>
                                <p className='m-0 p-0 font_header2'>Help Center</p>
                            </div>

                        </div>
                        <div className='col-md-12 mt-5 pb-5'>
                            <div className='row'>
                                <div className='col-md-6 m-auto '>
                                    <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                    Privacy Policy
                                    </p>
                                    <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                        <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> Privacy Policy</span>
                                    </p>
                                </div>
                                <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                    <img className='img-fluid' data-aos="zoom-in" src='/imagess/pp.png' />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className='col-md-12 universal_padding'>
                        <p className='m-0 p-0 yapay_head'>Privacy Policy</p>
                        <p className='m-0 p-0 yapay_head1'>
                            Grey’s services are provided by, and you’re contracting with: Grey Inc. organized under the laws of the State of Delaware, USA, and operating under the laws of the USA with its
                            registered address at 651 N Broad Street, Suite 206, Middletown DE 19700.
                            This privacy policy (this "Privacy Policy") explains how personal information is collected, used, stored, and disclosed by Grey. This Privacy Policy applies to our website and all
                            related sites, applications, services and tools regardless of how you access or use them. This Privacy Policy is part of our Terms of Use. By accessing or using our Services,
                            website, software, services, applications, products and content offered via Grey (collectively, the “Services”), you agree to this Privacy Policy and our Terms of Use.
                            This Privacy Policy applies to your use of (regardless of means of access) our Services. You may access or use our Services through a desktop, laptop, mobile phone, tablet, or
                            other consumers electronic device (each, a "Device").
                            This Privacy Policy does not apply to services that are not owned or controlled by Grey, including third-party websites and the services of other Grey merchants. These other
                            sites may place their own cookies, plug-ins or other files on your computer, collect data or solicit personal information from you. Grey does not control these third-party websites
                            and we are not responsible for their privacy statements. Please consult such third parties’ privacy statements.
                        </p>
                    </div>

                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>INFORMATION WE COLLECT</p>
                        <p className='m-0 p-0 yapay_head2'>a. Information You Provide Us</p>
                        <p className='m-0 p-0 yapay_head1'>
                            a. Information You Provide Us To gain full access to our website and services, you must register for a Grey account. When you register for an account, we collect Personal Information
                            which you voluntarily provide to us. Personal Information refers to information relating to an identified person or information that can be used to identify you, (e.g. email address,
                            bank details, name, telephone number). It may also include anonymous information that may be linked to you specifically, (e.g. IP address).
                            The Personal Information we have about you is directly made available to us when you:
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>Sign up for a Grey Account;</li>
                                <li>Use any of our services;</li>
                                <li>Contact us or our customer support team;</li>
                                <li>Fill our online forms;</li>
                            </ul>
                        </p>

                        <p className='m-0 p-0 yapay_head2'>b. Personal Information We May Collect About You</p>
                        <p className='m-0 p-0 yapay_head1'>
                            We may collect, use, process, store, or transfer personal information such as:
                            - Identity Data & Identification Documents: Information such as, your full name(s), your government-issued identity number, bank verification number (BVN) or NIN and your date
                            of birth. Identification documents may include passport or any Government-issued identity card, a photograph (if applicable) and any other registration information you may
                            provide to prove you are eligible to use our services. This data is to enable us to verify your identity in order to offer our services to you;
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>Contact Data: This is data that is needed to reach out to you, such as your contact address, email address, telephone number, details of the device you use and billing details;</li>
                                <li>Log/Technical information: When you access Grey’s services, our servers automatically record information that your browser sends whenever you visit a website, links you have
                                    clicked on, length of visit on certain pages, unique device identifier, log-in information, location and other device details.</li>
                                <li>Financial Data: Information, such as personal account number, the merchant’s name and location, the date and the total amount of transaction, and other information provided
                                    by financial institutions or merchants when we act on their behalf;</li>
                                <li>Transactional Data: These are information relating to payments when you as a merchant (using one or more of our payment processing services) or as a customer, are using
                                    our products or services;</li>
                                <li>
                                    Marketing and Communications Data: This includes both a record of your decision to subscribe or to withdraw from receiving marketing materials from us or from our third
                                    parties.
                                </li>
                            </ul>
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            Records of your discussions with us, if we contact you and if you contact us.
                        </p>
                    </div>

                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>HOW WE MAY USE YOUR PERSONAL INFORMATION</p>
                        <p className='m-0 p-0 yapay_head1'>
                            We may use the Personal Information we collect to:
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>Create and manage any accounts you may have with us, verify your identity, provide our services, and respond to your inquiries;</li>
                                <li>To administer Grey(i.e. to provide our Services to you) and for internal operations, including troubleshooting, data analysis, testing, research, statistical and survey purposes
                                    (i.e. to guarantee Grey’s stability and security) and to solicit your feedback</li>
                                <li>Process your payment transactions (including authorization, clearing, chargebacks and other related dispute resolution activities);</li>
                                <li>Protect against and prevent fraud, unauthorized transactions, claims and other liabilities;</li>
                                <li>Provide, administer and communicate with you about products, services, offers, programs and promotions of Grey, financial institutions, merchants and partners;</li>
                                <li>Evaluate and improve our business, including developing new products and services;</li>
                                <li>As necessary to establish, exercise and defend legal rights; As may be required by applicable laws and regulations, including for compliance with Know Your Customers and
                                    risk assessment, Anti-Money Laundering, anti-corruption and sanctions screening requirements, or as requested by any judicial process, law enforcement or governmental
                                    agency having or claiming jurisdiction over Aboki Africa or it’s affiliates;</li>
                                <li>To use data analytics to improve our Website, products or services, and user experiences.</li>
                                <li>For other purposes for which we provide specific notice at the time of collection.</li>
                            </ul>
                        </p>
                    </div>

                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>HOW WE SHARE YOUR PERSONAL DATA</p>
                        <p className='m-0 p-0 yapay_head1'>
                            We may disclose or share your Personal Information with third parties which include our affiliates, employees, officers, service providers, agents, suppliers, subcontractors as may be
                            reasonably necessary for the purposes set out in this policy.
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>
                                    We have your consent. We require opt-in consent for the sharing of any personal information; We share Personal Information with third parties directly authorized by you to
                                    receive Personal Information, such as when you authorize a third party application provider to access your account. The use of your Personal Information by an authorized third
                                    party is subject to the third party's privacy policy and Grey shall bear no liability for any breach which may arise from such authorization by you.
                                </li>
                                <li>We provide such information to our subsidiaries, affiliated companies or other trusted businesses or persons for the purpose of processing personal information on our behalf. </li>
                                <li>
                                    We require that these parties agree to process such information based on our instructions and in compliance with this Privacy Policy and any other appropriate confidentiality
                                    and security measures</li>
                                <li>We have a good faith belief that access, use, preservation or disclosure of such information is reasonably necessary to:
                                    satisfy any applicable law, regulation, legal process or enforceable governmental request,
                                    enforce applicable Terms of Service, including investigation of potential violations thereof
                                    detect, prevent, or otherwise address fraud, security or technical issues, or
                                    protect against imminent harm to the rights, property or safety of Grey, its users or the public as required or permitted by law</li>
                                <li>If Grey becomes involved in a merger, acquisition, or any form of sale of some or all of its assets, we will provide notice before personal information is transferred and become
                                    subject to a different privacy policy.</li>
                            </ul>
                        </p>
                    </div>

                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>OTHER RIGHTS TO YOUR PERSONAL INFORMATION WITH US</p>
                        <p className='m-0 p-0 yapay_head1'>
                            Below are the rights you have as a user in relation to your Personal Information;
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>Right to request access or copies to your Personal Information by contacting us</li>
                                <li>Right to information on their personal information collected and stored;</li>
                                <li>Right to correct or rectify any Personal Information that you provide which may be incorrect, out of date or inaccurate.</li>
                                <li>Right to object to the processing of your Personal Information for marketing purposes. You have a right to ask us not to contact you for marketing purposes by adjusting your
                                    notification preference on the settings page or by opting out via the unsubscribe link in marketing emails we send you.</li>
                                <li>Right to request that Grey erase your Personal Information. You have the right to ask us to erase your Personal Information. Please note that this is a limited right which applies
                                    where the data is no longer required, or the processing has no legal justification. The exceptions to this right is where the applicable law requires us to retain a historical archive
                                    or where we retain a core set of your personal data to ensure we do not inadvertently contact you in future where you object to your data being used for marketing purposes.</li>
                                <li>Right to object to decisions being taken by automated means which produce legal effects concerning you or similarly significantly affect you.</li>
                                <li>Right to request the movement of data from Grey to a third party; this is the right to the portability of data;</li>
                            </ul>
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            The basis of we processing your Personal Information is your consent. You also have the choice at any time to withdraw consent which you have provided.
                            You may decline to provide your personal Information when it is requested by Grey, however, certain services or all the services may be unavailable to you. You may review your
                            account settings and update your Personal Information directly or by contacting us.
                            If you wish to exercise any of the rights set above, please contact us using the contact information provided in the Contact Us segment below
                        </p>
                    </div>



                    <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                        <div className='row universal_padding'>
                            <div className='col-md-6 px-md-4'>
                                <img className='img-fluid' src='/imagess/b4.png' data-aos="fade-right" data-aos-duration="6000" />
                            </div>
                            <div className='col-md-6 m-auto'>
                                <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                    Download our App to get all kinds of
                                    banking benefits from anywhere
                                </p>
                                <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                    <img className='img-fluid width_gp' src='/imagess/googleplay.png' />
                                    <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.png' />
                                </div>
                            </div>

                        </div>


                    </div>

                    <Footer />
                </div>
            </main>
        </LoaderUniversal>
    )
}

export default Privacypolicy