import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect } from 'react'
import { LuDot } from "react-icons/lu";
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'

function Termsofuse() {
    useEffect(() => {
        setTimeout(function () {
        }, 6000);
        Aos.init({
            duration: 2000,
            easing: 'ease',
        });
    }, []);
    return (
        <LoaderUniversal>
            <Head>
                <title>YafPay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <LanguageHeader />
                <div className='col-md-12 background_color_universal'>
                    <div className='col-md-12 background_headerpp universal_padding'>
                        <div className='row pt-4'>
                            <div className='col-md-2 col-5'>
                                <Link href="/">
                                    <img className='img-fluid width_gp_l' src='/imagess/logo.png' />
                                </Link>
                            </div>
                            <div className='col-md-1 pt-2 col-2'>
                                <p className='m-0 p-0 font_header2'>Home</p>
                            </div>
                            <div className='col-md-1 pt-2 col-2' >
                                <p className='m-0 p-0 font_header2'>Blog</p>
                            </div>
                            <div className='col-md-1 pt-2 col-3'>
                                <p className='m-0 p-0 font_header2'>Help Center</p>
                            </div>

                        </div>
                        <div className='col-md-12 mt-5 pb-5'>
                            <div className='row'>
                                <div className='col-md-6 m-auto '>
                                    <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                                    Terms Of Service
                                    </p>
                                    <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                                        <span className='home_p'>Home</span><span className='home_p1'> <LuDot /> Terms Of Service</span>
                                    </p>
                                </div>
                                <div className='col-md-6 mt-md-0 mt-5 text-center'>
                                    <img className='img-fluid' data-aos="zoom-in" src='/imagess/tt.png' />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className='col-md-12 universal_padding'>
                        <p className='m-0 p-0 yapay_head'>Welcome to YAFPAY</p>
                        <p className='m-0 p-0 yapay_head1'>
                            This contract is between you and Grey Inc. (“Grey”, “we”, “us”, or “our” as applicable), and covers all aspects of your use of our Services, which include the website,
                            app and any other materials produced by Grey. These terms apply in full force and when you create a Grey Account, access our Services, or otherwise interact with us,
                            you agree to be bound by this Agreement and agree to receive communication relating to the Services or your Grey Account in electronic format. Additionally, you affirm
                            that you are at least eighteen (18) years old and legally allowed to enter into this Agreement. You expressly accept all Terms and Conditions contained herein in full and
                            without limitation or qualification, including our: Privacy Policy and Acceptable Use Policy. You must not use any of the Services if you have any objection to any of these
                            terms.<br />
                            It is essential that you read and understand all the terms of each of our policies as well as all the other agreements that are applicable to you. For certain Services,
                            we may have additional terms and conditions that we will communicate to you through the Service or by other means, and these supplementary terms and conditions
                            shall be included in this Agreement.
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>PURPOSE AND SCOPE OF AGREEMENT</p>
                        <p className='m-0 p-0 yapay_head1'>
                            This Terms of Service is an Agreement between you and Grey. It sets forth the terms and conditions that shall govern the use of the Platform and the services. It details
                            Grey’s obligations to you. It also highlights certain risks on using the services and you must consider such risks carefully as the provision of this Agreement will bind you
                            through your use of this website or any of our services.<br />
                            Our Services permit you to move money in supported currencies, send or receive money into your Grey Balance, keep amounts in your Grey Balance, convert currency balances
                            to balances in other supported currencies, pull out funds held in your Grey Balance, and send funds to recipients. We carry the sole authority to refuse to accept any user
                            or to complete any command to transmit, receive, send, withdraw or convert money held in your Grey Account at any time.
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>PURPOSE AND SCOPE OF AGREEMENT</p>
                        <p className='m-0 p-0 yapay_head1'>
                            <LuDot /> To use Grey, you have to create a Grey account by registering. To register, you will provide us with certain information such as your email, first name, last name, business
                            name and phone number and we may seek to verify your information, (by ourselves or through third parties), after which we will approve your account unless deemed
                            risky. You permit us to do all these.
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <LuDot /> In the event that you change any information provided to us at registration including your business name, address, financial institution, mode of payments or the products
                            and services that you offer, or where a corporate restructuring occurs, You agree to notify us within 14 days of such change. We may be unable to respond to you if you
                            contact us from an address, telephone number or email account that is not registered with us.
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>GETTING TO KNOW YOU</p>
                        <p className='m-0 p-0 yapay_head1'>
                            We are required by law to carry out all necessary security and customer due diligence checks on you (including any parties involved in your transaction e.g. your recipient) in order to
                            provide any services to you. You agree to comply with any request from us for further information and provide such information in a format acceptable to us. In addition, you agree
                            that we may make, directly or through any third party, any inquiries we consider necessary to validate the information you provided to us, including checking commercial databases or
                            credit reports. Grey reserves the right to close, suspend, or limit access to your Grey Account and/or the Services in the event we are unable to obtain or verify this information. You
                            authorize us to obtain one or more of your credit reports, from time to time, to establish, update or renew your Grey account with us or in the event of a dispute relating to this
                            agreement and activity under your Grey account.
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>ACCOUNT SECURITY</p>
                        <p className='m-0 p-0 yapay_head1'>
                            You are solely responsible for maintaining adequate security and control of any email IDs, passwords, or other details you use to access your Grey Account and Services. You agree
                            not to allow anyone else to have or use your password details and comply with all reasonable instructions regarding account access and security. In the event you share your
                            password details, Grey will not be liable to you for losses or damages. You will also take all reasonable steps to protect the security of the personal electronic device through which
                            you access Grey’s services (including, without limitation, enabling 2FA, using PIN and/or password-protected personally configured device functionality to access Grey’s services and
                            not sharing your device with other people). Immediately change your password and contact Grey customer support if:
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>anyone asks for your password, OTP or any other security-related aspect of your Grey Account.</li>
                                <li>your email address becomes compromised.</li>
                                <li>you suspect your Grey Account or login details including your password or any other security features are stolen, lost, used without authorization or otherwise compromised.</li>
                                <li>your transaction history for your Grey Account shows transactions that you did not initiate.</li>
                            </ul>
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            We may suspend your Grey Account or otherwise restrict its functionality if we have concerns about the security of the Grey Account or any of its security features; or potential
                            unauthorized or fraudulent use of your Grey Account or any of its security features
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>AGE RESTRICTION</p>
                        <p className='m-0 p-0 yapay_head1'>
                            Our website and services are directed to people aged 18 and above. You are only permitted to use the Services if you are 18 or older. We do not knowingly engage people younger
                            than the age of 18.
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>SOFTWARE LICENSE</p>
                        <p className='m-0 p-0 yapay_head1'>
                            For businesses, we hereby grant you a revocable, non-exclusive, non-transferable license to use Grey’s APIs, developer’s toolkit, and other software applications (the “Software”) in
                            accordance with the documentation accompanying the Software. This license grant includes all updates, upgrades, new versions and replacement software for your use
                            in connection with Grey’s services. If you do not comply with the documentation and any other requirements provided by Grey, then you will be liable for all resulting damages
                            suffered by you, Grey and third parties. Unless otherwise provided by applicable law, you agree not to alter, reproduce, adapt, distribute, display, publish, reverse engineer,
                            translate, disassemble, decompile or otherwise attempt to create any source code that is derived from the Software. Upon expiration or termination of this Agreement, you will
                            immediately cease all use of any Software.
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>WARRANTIES AND REPRESENTATIONS</p>
                        <p className='m-0 p-0 yapay_head1'>
                            You represent and warrant to Grey that:
                        </p>
                        <p className='m-0 p-0 yapay_head1'>
                            <ul className='mb-0'>
                                <li>You have the full power, authority, regulatory approval and corporate authorisation to enter into, execute, deliver and perform this Agreement.</li>
                                <li>You are duly organised, authorised and in good standing under the laws of any state, region or country of your organisation. You are duly authorised to do business in all other
                                    states, regions or countries in which your business operates.</li>
                            </ul>
                        </p>
                    </div>
                    <div className='col-md-12 universal_padding mt-5'>
                        <p className='m-0 p-0 yapay_head'>CHARGES AND FEES</p>
                        <p className='m-0 p-0 yapay_head1'>
                            You agree to pay us for the services we render. Our Fees will be calculated as demonstrated on the Pricing page on the website. Subject to the terms of this Agreement, Grey will
                            send to your designated bank or card settlement account (“Bank Account”) all amounts settled and due to you from your transactions, minus our stated fees, any Reversals,
                            Invalidated Payments, Chargebacks, Reversals, Refunds or other amounts that you owe to Grey under this Agreement (“Payout”). Should either Party in good faith have cause to
                            dispute any amount appearing on an invoice submitted by the other Party pursuant to this Agreement (“Affected Invoice”), the affected Party shall, within Forty-Eight (48) hours of
                            receipt of the Affected Invoice, notify the other Party in writing, of such dispute, specifying the Affected Invoice, the specific amount in dispute and alleged reasons or grounds for
                            dispute, failing which it will be deemed that the invoice is true and correct. We reserve the right to revise our fees. In the event that we revise our fees, we will notify you within
                            twenty-four (24) hours of such change.
                        </p>
                    </div>


                    <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
                        <div className='row universal_padding'>
                            <div className='col-md-6 px-md-4'>
                                <img className='img-fluid' src='/imagess/b4.png' data-aos="fade-right" data-aos-duration="6000" />
                            </div>
                            <div className='col-md-6 m-auto'>
                                <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                                    Download our App to get all kinds of
                                    banking benefits from anywhere
                                </p>
                                <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                                    <img className='img-fluid width_gp' src='/imagess/googleplay.png' />
                                    <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.png' />
                                </div>
                            </div>

                        </div>


                    </div>

                    <Footer />
                </div>
            </main>
        </LoaderUniversal>
    )
}

export default Termsofuse