import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LanguageHeader from '@/Components/LanguageHeader/LanguageHeader'
import Footer from '@/Components/Footer/Footer'
import "aos/dist/aos.css";
import Aos from "aos";
import { useEffect, useState } from 'react'
import Header from '@/Components/Header/Header'
import LoaderUniversal from '@/Components/LoaderUniversal/LoaderUniversal'
import Link from 'next/link'
import Button from 'react-bootstrap/Button';
import Collapse from 'react-bootstrap/Collapse';
import MobileHeader from '@/Components/MobileHeader/MobileHeader'

function VirtualCards() {
  useEffect(() => {
    setTimeout(function () {
    }, 6000);
    Aos.init({
      duration: 2000,
      easing: 'ease',
    });
  }, []);

  const [open1, setOpen1] = useState(false);
  const [open2, setOpen2] = useState(false);
  const [open3, setOpen3] = useState(false);
  const [open4, setOpen4] = useState(false);
  const [open5, setOpen5] = useState(false);
  const [open6, setOpen6] = useState(false);

  return (
    <>
      <Head>
        <title>YafPay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <LoaderUniversal>
          <LanguageHeader />
          <div className='col-md-12 background_color_universal'>
            <div className='col-md-12 background_header1 universal_padding'>
              <div className='row display_pc pt-4'>
                <div className='col-md-2 col-5'>
                  <Link href="/" className='link_style'>
                    <img className='img-fluid width_gp_l' src='/imagess/logo.webp' />
                  </Link>
                </div>
                <div className='col-md-1 pt-2 col-2'>
                  <Link href="/" className='link_style'>
                    <p className='m-0 p-0 font_header2'>Home</p>
                  </Link>
                </div>
                <div className='col-md-1 pt-2 col-2' >
                  <Link href="/Blogs" className='link_style'>
                    <p className='m-0 p-0 font_header2'>Blog</p>
                  </Link>
                </div>
                <div className='col-md-1 pt-2 col-3'>
                  <p className='m-0 p-0 font_header2'>Help Center</p>
                </div>

              </div>
              <div className='display_mob'>
                <MobileHeader />
              </div>
              <div className='col-md-12 mt-5 pb-5'>
                <div className='row'>
                  <div className='col-md-6 m-auto '>
                    <p className='m-0 p-0 banner1_heading' data-aos="fade-right" data-aos-duration="4000">
                      An Easier Way to<br />
                      Spend Globally
                    </p>
                    <p className='m-0 p-0 sub_heading_banner1 pt-3' data-aos="fade-right" data-aos-duration="3000">
                      Spend freely with a debit card that makes your international payments
                      easier. Get a Grey virtual card to shop, or pay for subscriptions and
                      gifts online anywhere in the world.
                    </p>
                    <div className='col-md-12 mt-md-1 pt-4'>
                      <img className='img-fluid width_gp' src='/imagess/googleplay.webp' data-aos="fade-right" data-aos-duration="4000" />
                      <img className='img-fluid ps-md-4 ps-2 width_gp' src='/imagess/apple.webp' data-aos="fade-right" data-aos-duration="3000" />
                    </div>
                    <div className='col-md-12 mt-md-3 mt-4'>
                      <div className='row'>
                        <div className='col-md-3 col-4 '>
                          <img className='img-fluid' data-aos="fade-right" data-aos-duration="4000" src='/imagess/people.webp' />
                        </div>
                        <div className='col-md-9 col-8 m-auto'>
                          <p className='m-0 p-0' data-aos="fade-left" data-aos-duration="3000"><span className='fivek'>500K+</span><span className='people ps-2'>People already trusted us.</span></p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className='col-md-6 mt-md-0 mt-5 text-center'>
                    <img className='img-fluid' data-aos="zoom-in" src='/imagess/banner-v1.webp' />
                  </div>
                </div>
              </div>
            </div>

            <div className='col-md-12 mt-5 pt-5 mb-5 pb-5'>
              <div className='row universal_padding'>
                <div className='col-md-6 m-auto'>
                  <div className='col-md-12  text-start'>
                    <p className='font_GBP mb-0' data-aos="zoom-in-up" data-aos-duration="4000">Why people choose us</p>
                    <p className='font_GBP3 mb-2' data-aos="zoom-in-up" data-aos-duration="4000">Banking Payments</p>
                    <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                      There are many variations of passages of Lorem Ipsum amet avoilble but majority
                      have suffered alteration in some form, by injected humur or randomise words which
                      don't sure amet sit dolor quras alto lorem.
                    </p>
                    <p className=' mb-1 points_currency' data-aos="zoom-in-left" data-aos-duration="6000">
                      Cards that work all across the world.
                    </p>
                    <p className=' mb-1 points_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                      Highest Returns on your investments.
                    </p>
                    <p className=' mb-1 points_currency ' data-aos="zoom-in-left" data-aos-duration="2000">
                      No ATM fees. No minimum balance. No overdrafts.
                    </p>
                  </div>
                  <div className='col-md-12 mt-4' data-aos="zoom-in-left" data-aos-duration="4000">
                    <img className='img-fluid' src='/imagess/signup.webp' />
                  </div>
                </div>
                <div className='col-md-6 text-center mt-5 mt-0'>
                  <img className='img-fluid' src='/imagess/banner-v2.webp' />
                </div>
              </div>
            </div>

            <div className='col-md-12 mt-5 pt-5 mb-5 pb-5'>
              <div className='row universal_padding_right'>
                <div className='col-md-6 text-start'>
                  <img className='img-fluid' src='/imagess/banner-c2.webp' />
                </div>
                <div className='col-md-6 m-md-auto mt-5 ps-4 px-md-0'>
                  <div className='col-md-12  text-start'>
                    <p className='font_GBP mb-0' data-aos="zoom-in-up" data-aos-duration="4000">Building a Positive Workplace Culture: A Foundation for Success
                      Happy Team, Thriving Dream: Workplace vibes that beam</p>
                    <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                      A happy crew makes success come true. When smiles fill the room, collaboration
                      blooms. Cheerful faces, and shared spaces - that's how we pave the way for success
                      in our day
                    </p>
                  </div>
                  <div className='row mt-4'>
                    <div className='col-md-6'>
                      <div className='col-md-12'>
                        <img className='img-fluid' src='/imagess/kl.webp' />
                        <p className='m-0 p-0 split'>Teamwork Gleam: Building the Dream Team's Scheme</p>
                        <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                          A happy team turns every goal into a gleam. When we unite, everything seems like
                          a dream. Teamwork's the theme, success is the stream. In our workplace, it's more
                          than just a scheme.
                        </p>
                      </div>
                    </div>
                    <div className='col-md-6'>
                      <div className='col-md-12'>
                        <img className='img-fluid' src='/imagess/ip.webp' />
                        <p className='m-0 p-0 split'>Cultivating Success: Fostering a Positive Workplace Culture</p>
                        <p className='p_text_currency' data-aos="zoom-in-left" data-aos-duration="4000">
                          Establishing a workplace culture of positivity is the cornerstone of a thriving and
                          successful team. The synergy of content and motivated individuals propels us
                          forward, ensuring collective success.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>


              </div>
            </div>


            

            <div className='col-md-12  background_header3 pt-5  px-md-5  pb-md-0 pb-5'>
              <div className='row universal_padding'>
                <div className='col-md-6 px-md-4'>
                  <img className='img-fluid' src='/imagess/b4.webp' data-aos="fade-right" data-aos-duration="6000" />
                </div>
                <div className='col-md-6 m-auto'>
                  <p className='text_section5 mt-md-0 mt-5' data-aos="fade-left" data-aos-duration="5000">
                    Download our App to get all kinds of
                    banking benefits from anywhere
                  </p>
                  <div className='col-md-12  pt-4' data-aos="fade-left" data-aos-duration="3000">
                    <img className='img-fluid width_gp' src='/imagess/googleplay.webp' />
                    <img className='img-fluid ps-md-4 width_gp ps-2' src='/imagess/apple.webp' />
                  </div>
                </div>

              </div>


            </div>
            <Footer />
          </div>
        </LoaderUniversal>
      </main>
    </>
  )
}

export default VirtualCards